### ISSUE TITLE
Windows effect enable failed.

### ISSUE THREAD

**Issue by anantamishra** [UbuntuDDE/bugs#1]
**Describe the bug**

**To Reproduce**
1. Upgrade the system with the latest update released.
2. Go to Controlcenter and try enabling the windows effect.
3. See the error

**Expected behavior**
Windows effect should be enabled from the control center.

**Desktop (please complete the following information):**
 - UbuntuDDE 20.04 Focal Fossa

**Additional context**
Temporary fix:
`edit  ~/.config/kwinrc
and edit the line with
OpenGLIsUnsafe=true to
OpenGLIsUnsafe=false`

**Comment by openarun** [comment]
I am closing this bug because focal is EOL and I believe the latest release of UbuntuDDE has this issue fixed. If you find this bug in the latest releases, please feel free to re-open and mention your UbuntuDDE Remix version.
