### ISSUE TITLE
WiFi issue

### ISSUE THREAD

**Issue by ackr-8** [UbuntuDDE/bugs#10]
I'm using the 20.04 release, and the WiFi doesn't work after suspend, and also I can't install the point release as I already have too many applications and files in the system.
Specs : 
AMD Ryzen 3 2200g
8GB RAM
240GB SSD
TP-LINK WI-FI N Wireless PCI-E adapter.

**Comment by anantamishra** [comment]
If the laptop wakes from sleep mode the WiFi wont’t work or won’t connect back to the previously connected network.

Here is the Simple way to fix that.

Open terminal and run the following command

`sudo nano /lib/systemd/system-sleep/wififix`

After entering the the Password, It will open the nano editor.

Now Paste the Below Code

`!/bin/sh
set -e
if [ "$2" = "suspend" ] || [ "$2" = "hybrid-sleep" ]; then
     case "$1" in
             pre) true ;;
             post) sleep 1 && service network-manager restart ;;
       esac
fi`

Press Ctrl+O and Enter to save it

Press Ctrl+X to close the file

Now, make this a executable using this command.

sudo chmod +x /lib/systemd/system-sleep/wififix

That’s it.

This Wifi not working issue fix tested on Ubuntu 20.04 Focal Fossa

**Comment by ackr-8** [comment]
Ok I'll try

**Comment by rkrockein** [comment]
the same issue happens when you are connected through USB tethering. After waking from sleep mode, when I click on USB tethering on phone, the system doesn't get connected.

**Comment by ackr-8** [comment]
The solution worked, thanks.
