### ISSUE TITLE
Shutdown menu not working

### ISSUE THREAD

**Issue by eduardo92005-debug** [UbuntuDDE/bugs#100]
When I try to shutdown my laptop through shutdown menu buttons doesn't works, so I've to shutdown my pc manually.

Version: 5.11.0-22-generic

**Comment by openarun** [comment]
Which version of UbuntuDDE Remix are you using?

**Comment by openarun** [comment]
I am closing this bug as I believe the latest release of UbuntuDDE has this issue fixed. If you find this bug in the latest releases, please feel free to re-open and mention your UbuntuDDE Remix version.
