### ISSUE TITLE
Ubuntu DE need to be updated

### ISSUE THREAD

**Issue by aluisco** [UbuntuDDE/bugs#101]
when try to see the release in Ubuntu 21.04 Hirsute say UbuntuDDE 20.10.

<a href="https://ibb.co/1fC5XN5"><img src="https://i.ibb.co/Kjtksgk/photo-2021-08-29-14-23-51.jpg" alt="photo-2021-08-29-14-23-51" border="0"></a>

Regards,
Aluisco

**Comment by openarun** [comment]
I am closing this bug as I believe the latest release of UbuntuDDE has this issue fixed. If you find this bug in the latest releases, please feel free to re-open and mention your UbuntuDDE Remix version.
