### ISSUE TITLE
dde+ process in Ubuntudde heats up the computer!

### ISSUE THREAD

**Issue by CzmilDos** [UbuntuDDE/bugs#102]
**Describe the bug**
Most of times I've been working in vs code, shell and there are also opened or reduced folders. When using the computer at one point, the CPU starts to heat up, the fan makes loud and continuous noise and ubuntudde runs very slowly. And when I run "top" command in the shell, it appears that a process called "dde+" is using 80-100% of the CPU. And when I kill that process the CPU cools down and the system runs softer until it starts to heat up again...
**To Reproduce**
1. Keep a browser opened or reduced
2. Also keep folders from deepin file manager reduced
3. Playing video in vlc
4. Be working in a IDE

**Expected behavior**
As I have a i5-1035G1 Intel CPU and 16GB of RAM, and we're just talking about opened folders and also one or two software, the CPU should not heats up that high

**Desktop (please complete the following information):**
 - Version 21.04

**Comment by openarun** [comment]
I am closing this bug as I believe the latest release of UbuntuDDE has this issue fixed. If you find this bug in the latest releases, please feel free to re-open and mention your UbuntuDDE Remix version.
