### ISSUE TITLE
Wifi disconnects and connects itself sometimes

### ISSUE THREAD

**Issue by CzmilDos** [UbuntuDDE/bugs#103]
Description
Sometimes when working, the wifi disconnects itself and u'll not get internet anymore... Seconds later it reconnects again until it disconnects few minutes later and so and soo

Desktop:
 - Version 21.04

**Comment by openarun** [comment]
I am closing this bug as I believe the latest release of UbuntuDDE has this issue fixed. If you find this bug in the latest releases, please feel free to re-open and mention your UbuntuDDE Remix version.
