### ISSUE TITLE
Can not click buttons

### ISSUE THREAD

**Issue by 8naf** [UbuntuDDE/bugs#106]
**Describe the bug**
The three button (`minimize`, `maximize` and `close` button) can not be clicked.

**To Reproduce**
1. Open `File Manager`
2. Click `minimize` button
3. Reopen `File Manager`
4. Click `maximize` button

**Expected behavior**
Can click those buttons.

**Screenshots**

https://user-images.githubusercontent.com/62730599/150683182-85633327-b604-407c-9181-13fa69e55bad.mp4

**Desktop (please complete the following information):**
 - Version: 20.04 LTS

**Additional context**
- Laptop: Thinkpad T470

**Comment by openarun** [comment]
I am closing this bug as I believe the latest release of UbuntuDDE has this issue fixed. If you find this bug in the latest releases, please feel free to re-open and mention your UbuntuDDE Remix version.
