### ISSUE TITLE
Theme setting bug

### ISSUE THREAD

**Issue by 8naf** [UbuntuDDE/bugs#107]
**Describe the bug**
Theme does not change when I click on other.
The `Control Center` does not automatically hide when I click outside of it.

**To Reproduce**
1. Open `Control Center`
2. Click `Theme` option
3. Select any theme 
4. Click outside of `Control Center`

**Screenshots**

https://user-images.githubusercontent.com/62730599/150684436-42605bec-ca13-47dd-ac13-a625928fca70.mp4

**Desktop (please complete the following information):**
 - Version: 20.04 LTS

**Additional context**
- Laptop: Thinkpad T470

**Comment by openarun** [comment]
I am closing this bug as I believe the latest release of UbuntuDDE has this issue fixed. If you find this bug in the latest releases, please feel free to re-open and mention your UbuntuDDE Remix version.
