### ISSUE TITLE
Cannot Install Vivaldi

### ISSUE THREAD

**Issue by joshontech** [UbuntuDDE/bugs#108]
**Describe the bug**
When downloading the .deb of vivaldi I cannot install it using the Package Installer due to broken dependencies libgcc-s1

**To Reproduce**
1. Go to vivaldi.com and download the .deb of vivaldi
2. Double click the .deb of vivaldi
3. Package installer reports broken dependencies: libgcc-s1

**Expected behavior**
Vivaldi gets installed like on other Ubuntu based distros.

**Screenshots**
![Screenshot 2022-01-28 165927](https://user-images.githubusercontent.com/44295541/151627494-cd7ea3fa-0b6b-4b78-8c97-1b0b091ef426.png)

**Desktop (please complete the following information):**
![Screenshot 2022-01-28 170138](https://user-images.githubusercontent.com/44295541/151627644-00333745-13b6-449d-9ac1-11a6b5e3f25a.png)

**Additional context**
Trying to install the missing dependency results in apt telling me its already installed.

**Comment by openarun** [comment]
Did you try installing with dpkg ?

**Comment by joshontech** [comment]
> Did you try installing with dpkg ?

I am sorry it took so long to get back to you on this. No I only tried the GUI gdebi installer.

**Comment by zarathustra-f90** [comment]
It works without issue if you install through terminal:
    `$ sudo apt install -f ~/Downloads/vivaldi-stable_5.1.2567.57-1_amd64.deb`
assuming you downloaded the deb file from Vivaldi site on your Downloads folder.
I used the most recent released stable version, change the filename to match your version.

**Comment by openarun** [comment]
I am closing this bug as I believe the latest release of UbuntuDDE has this issue fixed. If you find this bug in the latest releases, please feel free to re-open and mention your UbuntuDDE Remix version.
