### ISSUE TITLE
Dual Screen Not Working Straight After Boot Up

### ISSUE THREAD

**Issue by ivanivkovic** [UbuntuDDE/bugs#109]
Graphics card: 
NVIDIA GTX 1060 6GB

When I boot up the computer:
Primary screen: blank
Secondary screen: visible, no login form

To fix this I plug out the HDMI cable for the primary screen - form visible on the secondary.

I log in.

I plug in HDMI again, same issue.

I try plugging in and out a couple of times, now fine.

Let's make this deepin as user friendly so to attract more people and fix this :) lemme know what info you need

**Comment by ivanivkovic** [comment]
Ok this appeared the first couple of times but today it worked right away. Will post if it happens again.

**Comment by A1X5H04** [comment]
Close your issue if it is fixed

**Comment by openarun** [comment]
I am closing this bug as I believe the latest release of UbuntuDDE has this issue fixed. If you find this bug in the latest releases, please feel free to re-open and mention your UbuntuDDE Remix version.
