### ISSUE TITLE
Lightdm issue

### ISSUE THREAD

**Issue by ackr-8** [UbuntuDDE/bugs#11]
Everytime I turn on my PC after booting, the login screen turns black for a second and then works normally.
I'm using 20.04 release.

Steps to reproduce : 
Turn on your PC.

**Comment by anantamishra** [comment]
Can you enlist your device specification here along with the windows manager being used in your system right now

**Comment by ackr-8** [comment]
I'm using kwin as window manager. I have 2 devices both have the same issue, specs :
Device 1 : 
AMD Ryzen 3 2200g
8GB DDR4 RAM
22 " 1080p monitor

Device 2 :
AMD Ryzen 5 3500u
8GB LPDDR4 RAM
14" 1080p display

**Comment by ackr-8** [comment]
I'm attaching the crash reports, have a look.
[_usr_bin_lightdm-deepin-greeter.113.crash.pdf](https://github.com/UbuntuDDE/bugs/files/5134288/_usr_bin_lightdm-deepin-greeter.113.crash.pdf)

**Comment by ackr-8** [comment]
Issue still present in 20.10. Workaround as of now, setting gdm3 as dm instead of lightdm. But the theme is of Ubuntu and not DDE.

**Comment by geo68** [comment]
I have the same issue but in many cases the lightdm becomes black

**Comment by carloss66** [comment]
I am having the same issue on 20.10 on an Intel NUC8i5BEH.

![Screen Capture_select-area_20210114155843](https://user-images.githubusercontent.com/3195654/104654305-7cd47380-5681-11eb-964d-cd8a49556d35.png)

**Comment by danmoore2205** [comment]
I'm experiencing the same issue. As per @ackr-8's suggestion, I switched from lightdm to gdm3 and the issue does not occur now but the login screen is not dde.

**Comment by openarun** [comment]
I am closing this bug as I believe the latest release of UbuntuDDE has this issue fixed. If you find this bug in the latest releases, please feel free to re-open and mention your UbuntuDDE Remix version.
