### ISSUE TITLE
Bug of Deepin apps minimize button

### ISSUE THREAD

**Issue by zarathustra-f90** [UbuntuDDE/bugs#110]
**Describe the bug**
After a first minimize of a Deepin app (e.g. file explorer or terminal) then any subsequent
minimize of the same window fails as the minimize button cannot be pressed.
This only happens on Deepin apps not other apps.

**To Reproduce**
1. Open a Deepin app (e.g. Terminal)
2. Click on minimize button
3. Raise the terminal window
4. Click on minimize button

**Expected behavior**
Minimize button should be pressed and apply the minimization of window.

**Screenshots**

![Record_dde-desktop_20220316145343](https://user-images.githubusercontent.com/42153227/158596436-dd04179b-bf59-47c3-8e26-64d65b386fb2.gif)

**Desktop (please complete the following information):**
 - Version 21.10

**Additional context**
This happened on a fresh installed Ubuntu DDE 21.10.

**Comment by Maxence** [comment]
Same issue with 22.04

**Comment by openarun** [comment]
I was able to reproduce this issue, I will check further on it.

**Comment by openarun** [comment]
This bug has been fixed with the latest updates in kwin, you can upgrade your system by executing the following command in terminal.
`sudo apt update && sudo apt upgrade`

If the issue still persist, please feel free to reopen this issue and update more information with it.
Thanks!
