### ISSUE TITLE
Fix Rounded Corners of Dock 

### ISSUE THREAD

**Issue by A1X5H04** [UbuntuDDE/bugs#111]
UbuntuDDE doesn't have rounded corner dock, I have tried changing the window radius slider but no luck, if you are reading this, please fix it as it seems ugly I have also post this issue on deepin issues page...
![image_2022-04-05_23-24-49](https://user-images.githubusercontent.com/78891448/161867997-b834d23c-8af3-4640-ad75-2aac87ff4c95.png)
Please fix this....

**Comment by SheblMohamed** [comment]
> UbuntuDDE doesn't have rounded corner dock, I have tried changing the window radius slider but no luck, if you are reading this, please fix it as it seems ugly I have also post this issue on deepin issues page... ![image_2022-04-05_23-24-49](https://user-images.githubusercontent.com/78891448/161867997-b834d23c-8af3-4640-ad75-2aac87ff4c95.png) Please fix this....

same the bug, i hope anyone reply

**Comment by zhivkom** [comment]
I guess this is bugging everyone, but noone cares, since its been presented for quite some time

**Comment by Maxence** [comment]
Same issue, and some rounded cornor on other windows got a triangle.

**Comment by openarun** [comment]
Hi @Maxence yes, there is some incompatibility of dde-kwin again in the new release. Upstream is already working on it, we'll send the patches/updates as soon as it it rolled out.

**Comment by kooolarpan** [comment]
I am closing this bug as I believe the latest update has this issue fixed. If you find this bug in the latest update, please feel free to re-open this issue.

Please run the following command on the terminal:
```
sudo apt update
sudo apt upgrade
```
