### ISSUE TITLE
Screen lock login issues

### ISSUE THREAD

**Issue by SheblMohamed** [UbuntuDDE/bugs#112]
Hello
Can anyone here help me???
Why all the versions having the same bad bug?
The latest version having screen lock issues (sometimes booting and sometimes black screen!)
This bad bug on v21.10, 21.04, 20.10.
Is that really normal???
I tried all the versions but really no anyone stable!
Can anyone's please help??
I love this distribution and i don't wanna leave so i hope someone helps
Thanks

**Comment by openarun** [comment]
I am closing this bug as I believe the latest release of UbuntuDDE has this issue fixed. If you find this bug in the latest releases, please feel free to re-open and mention your UbuntuDDE Remix version.
