### ISSUE TITLE
UbuntuDDE 22.04 crashes with KWin is unstable message

### ISSUE THREAD

**Issue by gsshiva** [UbuntuDDE/bugs#113]
**Describe the bug**
Installed UbuntuDDE desktop package on top of Ubuntu 22.04 (using this [link](https://computingforgeeks.com/install-deepin-desktop-environment-on-ubuntu/)) and the installation went successful. 

After a reboot, when login, I keep getting "Kwin is unstable" message multiple times and after a while the dock completely disappears. The only way to interact with the system is using the context menu,  so that I can launch the terminal and reboot.

I also created a Bootable `UbuntuDDE` USB and tried to install natively on a MacbooPro and the installer had the same issues as installing DDE on top of Ubuntu. I also tried using the ISO to install on a VM, on a Mac (using qemu) and it has same issues. But I was able to run Deepin OS latest community version  on my Mac with out any of the issues. I am not sure if the DDE on UbuntuDDE and DeepinOS are the same binary. 

**To Reproduce**
I am able to reproduce it on the following systems
1. MacBook Pro 2009
2. Lenovo ideaPad
3. On a VM (using QEMU) on MacOS Monterey

**Expected behavior**
Expected to use Deepin Desktop.

**Screenshots**

**Desktop (please complete the following information):**
 - Version 22.04.01

**Additional context**

**Comment by dchurch315** [comment]
I can add that I am able to cause this issue by simply changing the theme from light to either auto or dark on a VirtualBox install (with 3d), an Asus Vivobook install and even in the live installer environment on both of these.

**Comment by anantamishra** [comment]
I am closing this bug as an update has been released for the issue. The issue no more persists after performing a update of the system.

Please run the following command on the terminal to update your system:
```
sudo apt update
sudo apt upgrade
```
If the issue stills persists on your system, please feel free to reopen the issue.
