### ISSUE TITLE
Rounded corner window rendering with black corners

### ISSUE THREAD

**Issue by maustange** [UbuntuDDE/bugs#115]
After installing the nVidia driver the rounded corners of the windows have a black background.

![border](https://user-images.githubusercontent.com/44899425/192165993-9c6c1d79-b317-4f26-a1cc-64b65cd7b16b.jpg)

**Comment by kooolarpan** [comment]
I am closing this bug as I believe the latest update has this issue fixed. If you find this bug in the latest update, please feel free to re-open this issue.

Please run the following command on the terminal:
```
sudo apt update
sudo apt upgrade
```
