### ISSUE TITLE
Wrong DE version on descriptions

### ISSUE THREAD

**Issue by aluisco** [UbuntuDDE/bugs#116]
**Describe the bug**
Just a small bug at the time of know the ubuntudde version.

**To Reproduce**
1. Go to console
2. Execute neofetch
3. See error

**Screenshots**
<a href='https://postimages.org/' target='_blank'><img src='https://i.postimg.cc/J4m7PPCw/Screen-Capture-select-area-20220926090429.png' border='0' alt='Screen-Capture-select-area-20220926090429'/></a>

**Desktop (please complete the following information):**
 - Version [e.g. 22.04]

**Comment by openarun** [comment]
A reupload has been made addressing this issue. https://launchpad.net/~ubuntudde-dev/+archive/ubuntu/stable/+build/24524893

**Comment by openarun** [comment]
Fix is released!
