### ISSUE TITLE
Dist-upgrade on UbuntuDDE Remix 22.04 remove unbuntudde-dde

### ISSUE THREAD

**Issue by sfvaleriano** [UbuntuDDE/bugs#117]
After apt-get update/upgrade and dist-upgrade unbuntudde-dde was removed and replaced by kde plasma

1. Fresh installation of UbuntuDDE Remix 22.04
2. sudo apt-get update
3. sudo apt-get upgrade
4. sudo apt-get dist-upgrade

ubuntudde-dde was removed and replaced by kde plasma

**Comment by openarun** [comment]
There were some package conflicts.
The issue has been resolved with the latest package updates. Please try to upgrade now :)
