### ISSUE TITLE
PackageKit Error

### ISSUE THREAD

**Issue by eldy007** [UbuntuDDE/bugs#118]
**Describe the bug**
after fresh install i got this message when try to download from dde-store

**Expected behavior**

**Screenshots**
![IMG_20230129_212907_032](https://user-images.githubusercontent.com/123900755/215352148-268c79f5-7d83-4af3-b628-b7d4a80523b9.jpg)
![IMG_20230129_213842_566](https://user-images.githubusercontent.com/123900755/215352159-29cd2aa9-a3f8-40dd-8173-1fafbc43bbe9.jpg)

**Desktop (please complete the following information):**
 - Version Ubuntu 22.04.1 LTS x86_64

**Additional context**

**Comment by openarun** [comment]
A fix has been released with dde-store version 1.2.4. Please upgrade the store. Hope that solves your issue. :)

**Comment by eldy007** [comment]
now it working.
