### ISSUE TITLE
Battery Icon problem

### ISSUE THREAD

**Issue by architlatkar27** [UbuntuDDE/bugs#12]
**Describe the bug**
Battery Icon is unable to identify if the charger is connected

**To Reproduce**
1. Connect charger to laptop, switch on power. Battery icon will show that it is charging.
2. Put the system in sleep mode.
3. Unplug the charger
4. The icon should have reverted back. However it still indicates that the charger is plugged.

**Expected behavior**
Battery icon indicates that the charger is plugged which is not the case.

**Screenshots**

**Desktop (please complete the following information):**
 - Version 20.04

**Additional context**

**Comment by openarun** [comment]
I am closing this bug as I believe the latest release of UbuntuDDE has this issue fixed. If you find this bug in the latest releases, please feel free to re-open and mention your UbuntuDDE Remix version.
