### ISSUE TITLE
deepin-compressor not working

### ISSUE THREAD

**Issue by holzboa** [UbuntuDDE/bugs#121]
deepin-compressor: error while loading shared libraries: libcompressor-interface.so: cannot open shared object file: No such file or directory

`/usr/lib/x86_64-linux-gnu/deepin-compressor/plugins/libcompressor-interface.so` is in place

Happens on UbuntuDDE 23.04

**Comment by openarun** [comment]
The issue has been resolved and a fix has been released.
Please upgrade your deepin-compressor.

```
sudo apt update
sudo apt install deepin-compressor
```
