### ISSUE TITLE
Desktop rotation issue

### ISSUE THREAD

**Issue by Looksmart01** [UbuntuDDE/bugs#13]
I would like to report a problem on the rotation of the screen. When I tried to do it with the built-in touchpad on my Dell Vostro 3360 notebook, after the first rotation the mouse cursor hides under the white square and it doesn't allow me any action anymore. After that the only way to straighten the screen is to open the terminal and use the xrandr command, typing "xrandr - o normal". When I restart the desktop is rotated again and only by inserting an external mouse I can put everything back in place. With external mouse the problem doesn't happen

**Comment by openarun** [comment]
Hi there,
Try installing an appropriate driver for your touchpad once. If it doesn't work  try to make the above command to run in every boot. :)
Hope that helps you. Feel free to reopen the issue if the issue persists.
Thanks !

**Comment by Looksmart01** [comment]
Hi,
where can i find an appropriate driver for my touchpad for ubuntu dde?
