### ISSUE TITLE
Laptop Keyboard Not Working after updates 

### ISSUE THREAD

**Issue by tony1ant** [UbuntuDDE/bugs#14]
Hi Every1
I have an Acer Aspire E5-511 laptop. A few days ago I updated the software and after the updates my laptop kybd stopped working. My bluetooth kybd works, so do my USB and my wireless 2.4ghz kybds. I have searched Google and I cant find anything for UbuntuDDE regarding my kybd not working. I've made a few posts on the Telegram channel a few times, but I got No replies. Its taken me many weeks to set up and install all the apps I need & use, so I'd like to avoid if possible having to do a new fresh install. I also updated & upgraded  in terminal and I still can't get my kybd to work. 
My keyboard is Not faulty, because it works in the Bios settings and if I run UbuntuDDE (or any other distro) from a live CD, USB SSD, USB HDD & USB or a live USB mem stick-flash drive it works as well.  

Could some1 Please help, cause I'm going bald from pulling out my hair trying to get my kybd to work?
Thank you in advance.

**Comment by noyyyy** [comment]
Maybe you could just enable it by `xinput --enable id`( for instance, `xinput --enble 11`). You can see the id by `xinput`

**Comment by openarun** [comment]
I am closing this bug as I believe the latest release of UbuntuDDE has this issue fixed. If you find this bug in the latest releases, please feel free to re-open and mention your UbuntuDDE Remix version.
