### ISSUE TITLE
Password box not working after awake if I use Amazon workspace in full screen

### ISSUE THREAD

**Issue by rindia** [UbuntuDDE/bugs#15]
Hi,
I am using Amazon workspace and if i use it on full screen mode and my system is ideal for couples of minutes and reback to awake then UbuntuDDE ask passy to login.

Problem - password box or any other functionality not working on login screen. If I type password it type the word on my workspace screen.
In that case I restart the system forcely.
![IMG_20200921_133549_621](https://user-images.githubusercontent.com/22998037/93839908-0e237280-fcac-11ea-9644-d1a518cb8e0b.jpg)
![IMG_20200921_133609_434](https://user-images.githubusercontent.com/22998037/93839909-0fed3600-fcac-11ea-88a0-95f813fbfebe.jpg)

**Comment by noyyyy** [comment]
I have similar problems. My solution is to type `Ctrl+Alt+Fn+F2` to tty2 and login. Then `service lightdm restart`, which may be  friendlier for hardware.

**Comment by openarun** [comment]
I am closing this bug as I believe the latest release of UbuntuDDE has this issue fixed. If you find this bug in the latest releases, please feel free to re-open and mention your UbuntuDDE Remix version.
