### ISSUE TITLE
UbuntuDDE Beta 20.10 calendar format

### ISSUE THREAD

**Issue by aeropatron** [UbuntuDDE/bugs#17]
The calendar first day of the week is by default Sunday, once you install extra language supports (spanish in my case), one calendar option change to week starts on Monday (correct). But actually no changes at calendar that keep showing each week starting on Sundays.

Also at calendar options, on short formats available, everyone of them starts with year, the correct one is not present, should be: 30/6/2020.

**Comment by scroom** [comment]
opened a bug report in the deepin repo:
https://github.com/linuxdeepin/dde-calendar/issues/41

**Comment by scroom** [comment]
opened as well a bug report in the deepin repo for the second aspect:
https://github.com/linuxdeepin/dde-calendar/issues/40

**Comment by openarun** [comment]
I am closing this bug because groovy is EOL and I believe the latest release of UbuntuDDE has this issue fixed. If you find this bug in the latest releases, please feel free to re-open and mention your UbuntuDDE Remix version.
