### ISSUE TITLE
Square corners on dock (20.10 Beta)

### ISSUE THREAD

**Issue by dylanmartinezs** [UbuntuDDE/bugs#19]
**Describe the bug**
The Deepin 20 dock has square, sharp edges instead of the round ones seen in the main OS.

**To Reproduce**
It's visible as UbuntuDDE starts

**Expected behavior**
Borders should be round, maybe controlled by the non-present option of roundness seen [here](https://www.youtube.com/watch?v=-O8odkvbwhU)

**Screenshots**
![photo_2020-10-05_18-59-25](https://user-images.githubusercontent.com/25688218/95109950-98a0b300-073d-11eb-94cf-9f4aecd3202f.jpg)

**Desktop (please complete the following information):**
 - Version 20.10 Beta

**Additional context**
Not needed.

**Comment by anantamishra** [comment]
This issue is UbuntuDDE 20.10 Beta has been resolved and no more existing.

In the meanwhile, I would also like to inform you that UbuntuDDE 20.10 Final Release has been launched, you can download the ISO from UbuntuDDE Website and switch to stable release.

Thanks.

**Comment by openarun** [comment]
I am closing this issue as its fixed in the latest update/release. If you have any issue ahead related to this bug, please don't hesitate to reopen.
Thanks! :)
