### ISSUE TITLE
Notification Center icon not showing in dock (20.10 Beta)

### ISSUE THREAD

**Issue by dylanmartinezs** [UbuntuDDE/bugs#20]
**Describe the bug**
In the preview, and in Deepin demos, there's a notification button which opens notification center. This button isn't present in the installed version.

**To Reproduce**
1. Fresh install UbuntuDDE 20.10
2. Enable Notification Center plugin in the dock (if not enabled)

**Expected behavior**
The Notification Center button should appear in the dock.

**Screenshots**
![photo_2020-10-05_19-16-05](https://user-images.githubusercontent.com/25688218/95111162-67c17d80-073f-11eb-9bb1-04e0f72c383e.jpg)

**Desktop (please complete the following information):**
 - Version 20.10 Beta

**Additional context**
I had a home folder from a previous default Ubuntu installation, but it shouldn't affect at all.

**Comment by dylanmartinezs** [comment]
Edit, I've managed to show it by enabling and disabling it in settings, but then this happens
![photo_2020-10-05_19-27-50](https://user-images.githubusercontent.com/25688218/95112357-203bf100-0741-11eb-8701-c1a35cf55770.jpg)

**Comment by ackr-8** [comment]
Even I am facing the same issue

**Comment by anantamishra** [comment]
Hi there,
This issue was already fixed and the patch was sent via updates. And can't reproduce it anymore.
Feel free to reopen if it's an issue again with appropriate steps to reproduce.
Thanks!
