### ISSUE TITLE
UbuntuDDE 20.10 Beta WIFI access not listed

### ISSUE THREAD

**Issue by aeropatron** [UbuntuDDE/bugs#21]
I can see some WIFI spots, but mine is not listed.

I turn it off and one, i connected compueter to ethernet cable LAN to update.
Nothing worked.

If I mannually edit the SSID and password of my wifi, as it was a hidden network it works.

**Comment by hbarsaiyan** [comment]
I can confirm this

**Comment by MrPancakes39** [comment]
Me too

**Comment by MrPancakes39** [comment]
I can double confirm this

**Comment by anantamishra** [comment]
The patch has been released for this issue, please update your system to apply the patch.

```
sudo apt update && sudo apt upgrade
