### ISSUE TITLE
No themes option for GTK applications (20.10 Beta)

### ISSUE THREAD

**Issue by dylanmartinezs** [UbuntuDDE/bugs#22]
**Describe the bug**
In the Control Center, there should be an option of switching themes for non-Deepin apps (such as Software Center or Libreoffice). However, that option isn't there. Furthermore, gnome-tweaks does nothing at all.

**To Reproduce**
Go to Settings > Personalization.

**Expected behavior**
There should be a button or an option for switching GTK themes.

**Screenshots**
Not needed

**Desktop (please complete the following information):**
 - Version 20.10 Beta

**Additional context**
Not needed.

**Comment by openarun** [comment]
You can try to change with a KDE Windows Decoration than GTK but its not recommended at all to use other windows decorations than provided at the moment.
Thanks !

**Comment by openarun** [comment]
I am closing this bug because groovy is EOL and I believe the latest release of UbuntuDDE has this issue fixed. If you find this bug in the latest releases, please feel free to re-open and mention your UbuntuDDE Remix version.
