### ISSUE TITLE
Window becomes translucent if opened from window preview in dock in 20.10 beta

### ISSUE THREAD

**Issue by hbarsaiyan** [UbuntuDDE/bugs#23]
**Describe the bug**
The window of other program becomes translucent and overlaps with first program if it is opened from window preview in dock.

**To Reproduce**
1. Go to window preview of another program in dock
2. Click on it
3. See error

**Expected behavior**
The other program opens up

**Screenshots**
![Screen Capture_20201008145925](https://user-images.githubusercontent.com/37732050/95440764-efdd9800-0976-11eb-9af0-8b238677b92e.png)

**Desktop (please complete the following information):**
 20.10 beta

**Comment by anantamishra** [comment]
This issue has been fixed in the latest release of UbuntuDDE i.e: UbuntuDDE 20.10 .
You can navigate to  https://ubuntudde.com/download/ for the latest release.
If you have any issue ahead related to this bug, please don't hesitate to reopen.
Thanks! :)
