### ISSUE TITLE
Unable to change lockscreen wallpaper in 20.10 beta

### ISSUE THREAD

**Issue by hbarsaiyan** [UbuntuDDE/bugs#24]
**Describe the bug**
Unable to change lockscreen wallpaper in 20.10 beta

**To Reproduce**
1. Go to 'wallpaper and screensaver'
2. Click on 'only lockscreen' for a wallpaper

**Expected behavior**
Lock screen wallpaper changes to chosen wallpaper

**Desktop (please complete the following information):**
 20.10 beta

**Comment by anantamishra** [comment]
This issue is no more existing in UbuntuDDE 20.10 Beta.

And UbuntuDDE 20.10 Stable Release has been launched.

**Comment by openarun** [comment]
I am closing this issue as its fixed in the latest update/release. If you have any issue ahead related to this bug, please don't hesitate to reopen.
Thanks! :)
