### ISSUE TITLE
Notification panel blur offset

### ISSUE THREAD

**Issue by hbarsaiyan** [UbuntuDDE/bugs#25]
**Describe the bug**
The blur in Notification panel is misplaced.

**To Reproduce**

1. Click on 'Notifications' from dock
2. See error

**Screenshots**
![Screen Capture_20201014112638](https://user-images.githubusercontent.com/37732050/95949532-80512800-0e10-11eb-8992-4565f1040ec4.png)

**Desktop (please complete the following information):**
 - Version 20.10

**Comment by anantamishra** [comment]
Hi @hbarsaiyan , these problems are occurring due to the issue with dde-kwin are we are working with it to fix the issue, hope it resolves soon.

**Comment by anantamishra** [comment]
Hello @hbarsaiyan 
The patch has been released for this issue, please update your system to apply the patch.

```
sudo apt update && sudo apt upgrade
