### ISSUE TITLE
The deepin-wine QQ and Wechat can not be installed

### ISSUE THREAD

**Issue by Lesliewxj** [UbuntuDDE/bugs#26]
**Describe the bug**
the deepin-wine can not be installed ,because the deepin version is 2.18,but I installed this version it can't work fine.

**Desktop :**
 - Version:20.04

**Comment by openarun** [comment]
Hi @Lesliewxj , the package deepin-wine is not available in the repository of UbuntuDDE Remix 20.04.

**Comment by Lesliewxj** [comment]
but how to install the qq and wechat?

**Comment by openarun** [comment]
You can download the deb file and install QQ from their site : https://im.qq.com/linuxqq/download.html
To install wechat, you can install it from the Software Center named as "electronic wechat"

**Comment by Lesliewxj** [comment]
thanks a lot!
