### ISSUE TITLE
Applications Won't Minimize More Than Once

### ISSUE THREAD

**Issue by Hyperdraw** [UbuntuDDE/bugs#27]
**Describe the bug**
All applications that are part of the Deepin Desktop Environment (like the file manager, text editor, etc.) can minimize once, but then if you restore them and try to minimize them again, it does nothing. The issue doesn't seem to happen with other applications (e.g. Firefox), but only with DDE applications.

**To Reproduce**
1. Open an application that is part of the Deepin Desktop Environment
2. Minimize the window
3. Restore the window
4. Try to minimize it again

**Expected behavior**
A window that has already been minimized once and then restored should still be able to minimize again.

**Desktop:**
 - Version 20.10

**Comment by anantamishra** [comment]
The patch for this issue is applied in the latest update/release.

You can now try updating the system or, switching to the stable release.
