### ISSUE TITLE
Boot on and Shutdown Sound Effects not Working.

### ISSUE THREAD

**Issue by MrPancakes39** [UbuntuDDE/bugs#28]
**Describe the bug**
Like the title says the boot on and shutdown sound effects won't work.

**To Reproduce**

Make sure you have these sound effects *enabled* if they aren't:
1. Go to Setting.
2. Click on Sound.
3. Click on Sound Effects.
4. Make sure Boot up and Shutdown have a checkmark next to them.

**Expected behavior**
When booting up and/or shutdown the PC hearing the booting up and/or shutdown sound effects respectively.

**Desktop: UbuntuDDE**
 - Version: 20.10.

**Additional context**
This is on a fresh install of UbuntuDDE 20.10.

**Comment by Schykle** [comment]
Thought I'd drop some details here. I am currently able to hear startup/boot sounds, but I am not hearing the shutdown sounds. Likely related.

**Comment by openarun** [comment]
I am closing this bug because groovy is EOL and I believe the latest release of UbuntuDDE has this issue fixed. If you find this bug in the latest releases, please feel free to re-open and mention your UbuntuDDE Remix version.
