### ISSUE TITLE
Lock Screen Password Always Wrong

### ISSUE THREAD

**Issue by Schykle** [UbuntuDDE/bugs#30]
**Describe the bug**
Lock screen password is always incorrect, no matter the user or if the password matches the users'.

**To Reproduce**
1. Log into an user account
2. Lock the screen via `Super`+`L` (this is also consistent with waiting for the lock screen to trigger automatically)
3. Attempt to log in with the users' password
4. Password will not be correct, despite matching the login password

**Expected behavior**
Lock screen password should match users' login password and allow access to the locked session

Ubuntu DDE Remix 20.10, all packages up to date as of posting.

**Some System Info**

```
System:    Kernel: 5.8.0-26-generic x86_64 bits: 64 compiler: gcc v: 10.2.0 Desktop: Deepin 20.10 
           Distro: Ubuntu 20.10 (Groovy Gorilla) 
Machine:   Type: Desktop Mobo: ASUSTeK model: PRIME B350-PLUS v: Rev X.0x serial: <filter> UEFI: American Megatrends 
           v: 5407 date: 12/31/2019 
CPU:       Info: 8-Core model: AMD Ryzen 7 2700 bits: 64 type: MT MCP arch: Zen+ rev: 2 L2 cache: 4096 KiB 
           flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm bogomips: 108792 
           Speed: 1360 MHz min/max: 1550/3400 MHz boost: disabled Core speeds (MHz): 1: 1359 2: 3084 3: 1359 4: 1359 
           5: 1375 6: 1372 7: 1374 8: 1375 9: 1359 10: 1359 11: 1377 12: 1375 13: 1376 14: 1374 15: 1360 16: 2810 
Graphics:  Device-1: Advanced Micro Devices [AMD/ATI] Navi 10 [Radeon RX 5600 OEM/5600 XT / 5700/5700 XT] 
           vendor: XFX Pine driver: amdgpu v: kernel bus ID: 0c:00.0 
           Display: x11 server: X.Org 1.20.9 driver: amdgpu,ati unloaded: fbdev,modesetting,radeon,vesa 
           resolution: 3840x1080~144Hz 
           OpenGL: renderer: AMD Radeon RX 5700 XT (NAVI10 DRM 3.38.0 5.8.0-26-generic LLVM 11.0.0) v: 4.6 Mesa 20.2.1 
           direct render: Yes 
Audio:     Device-1: Creative Labs Sound Core3D [Sound Blaster Recon3D / Z-Series] driver: snd_hda_intel v: kernel 
           bus ID: 09:00.0 
           Device-2: Advanced Micro Devices [AMD/ATI] Navi 10 HDMI Audio driver: snd_hda_intel v: kernel bus ID: 0c:00.1 
           Device-3: Advanced Micro Devices [AMD] Family 17h HD Audio vendor: ASUSTeK driver: snd_hda_intel v: kernel 
           bus ID: 0e:00.3 
           Device-4: Logitech HD Pro Webcam C920 type: USB driver: snd-usb-audio,uvcvideo bus ID: 1-1.3:4 
           Device-5: C-Media Blue Snowball type: USB driver: hid-generic,snd-usb-audio,usbhid bus ID: 3-4:2 
           Device-6: Kingston HyperX 7.1 Audio type: USB driver: hid-generic,snd-usb-audio,usbhid bus ID: 1-9:6 
           Sound Server: ALSA v: k5.8.0-26-generic 
Network:   Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet vendor: ASUSTeK driver: r8169 v: kernel 
           port: f000 bus ID: 04:00.0 
           IF: enp4s0 state: up speed: 1000 Mbps duplex: full mac: <filter> 
Drives:    Local Storage: total: 6.60 TiB used: 671.45 GiB (9.9%) 
           ID-1: /dev/nvme0n1 vendor: Samsung model: SSD 960 EVO 250GB size: 232.89 GiB 
           ID-2: /dev/sda vendor: Western Digital model: WDS500G2B0A-00SM50 size: 465.76 GiB 
           ID-3: /dev/sdb vendor: Western Digital model: WDS500G2B0A-00SM50 size: 465.76 GiB 
           ID-4: /dev/sdc vendor: Western Digital model: WDS500G2B0A-00SM50 size: 465.76 GiB 
           ID-5: /dev/sdd type: USB vendor: Western Digital model: WD easystore 2624 size: 4.55 TiB 
           ID-6: /dev/sde vendor: Western Digital model: WDS500G2B0A-00SM50 size: 465.76 GiB 
Partition: ID-1: / size: 230.88 GiB used: 33.28 GiB (14.4%) fs: btrfs dev: /dev/nvme0n1p3 
           ID-2: /boot size: 975.9 MiB used: 227.8 MiB (23.3%) fs: ext4 dev: /dev/nvme0n1p2 
           ID-3: /home size: 230.88 GiB used: 33.28 GiB (14.4%) fs: btrfs dev: /dev/nvme0n1p3 
Swap:      ID-1: swap-1 type: zram size: 1024.0 MiB used: 0 KiB (0.0%) dev: /dev/zram0 
Sensors:   System Temperatures: cpu: 29.0 C mobo: N/A gpu: amdgpu temp: 48.0 C 
           Fan Speeds (RPM): N/A gpu: amdgpu fan: 0 
Info:      Processes: 409 Uptime: 5h 17m Memory: 31.36 GiB used: 1.93 GiB (6.1%) Init: systemd runlevel: 5 Compilers: 
           gcc: 10.2.0 Packages: 1950 Shell: Bash v: 5.0.17 inxi: 3.1.07
```

**Comment by sdlins** [comment]
@Schykle, I have this exact same problem, unfortunately.

If you know a workaround (or anyone else knows), please, let us know.
Thanx for reporting that. I came here to do that but I found your reporting.

Edit: 
I tryed to switch from lightdm to gdm3 but, even although the first loggin happens on GDM, after I lock the screen (`super`+`L`) the password screen does not use gdm, but the lightdm, so the problem continues! And I can't remove lightdm cause `ubuntudde-minimal` depends on it.

😢

**Comment by sdlins** [comment]
I installed UbuntuDDE 20.04 in the same laptop (I removed 20.10) and I can confirm that it doesn`t happen in 20.04. It works perfectly.

**Comment by artti-jaakkola** [comment]
Installed Ubuntu DDE yesterday and I have the same problem. 

Trying to change password in settings causes the same error. 

passwd command in console works fine.

Using LUKS+btrfs, Apple keyboard, German layout.

**Comment by artti-jaakkola** [comment]
I noticed the lock screen works first, but stops later. I didn't pay much attention to it, but it might have something to do with adding another user. Just a guess. Moved to another distro for now.

**Comment by nlbi21** [comment]
Same problem here, this morning I created a new user for my daughter to use (before only I had an account), and the problem started. The strange thing is that I can not enter the account after blocking it, but I can enter my daughter's account without any problem.

I have ubuntudde with ubuntu 20.10

**Comment by oscarhc** [comment]
I upgraded UbuntuDDE from 21.04 to 21.10 having the issue in both versions.
Tried the ["login loop" fix](https://letsfoss.com/ubuntu-login-loop-fix/) but didn't work

**Comment by openarun** [comment]
I am closing this bug as I believe the latest release of UbuntuDDE has this issue fixed. If you find this bug in the latest releases, please feel free to re-open and mention your UbuntuDDE Remix version.
