### ISSUE TITLE
Compositing Is Disabled When Games Are Fullscreen & No Option To Disable This

### ISSUE THREAD

**Issue by Schykle** [UbuntuDDE/bugs#34]
**Describe the bug**
When launching and playing games like CS:GO from Steam, the compositor gets disabled, which causes window effects to stop working such as transparency, window smooth corners, blur, etc. There seems to be no toggle for this in Control Center, like KDE offers. Perhaps a command-line switch could be exposed?

**To Reproduce**
1. Ensure Window Effects are enabled
2. Launch a game such as CSGO fullscreen
3. Tab Out from the game, all window effects are disabled, and toggling this back does nothing while it's running.

**Expected behavior**
Users should be able to disable automatic compositing shutoff as this can cause inconsistencies in the UI as well as other breakages. Perhaps some command line switch might be able to address this?

**Screenshots**
Before launching game:
![image](https://user-images.githubusercontent.com/58709504/98068058-41633080-1e18-11eb-8615-199ea99d643b.png)
After launching game and tabbing out:
![image](https://user-images.githubusercontent.com/58709504/98068089-55a72d80-1e18-11eb-82a7-5066b4b4875e.png)

Ubuntu DDE 20.10, all packages up to date as of the time of posting.

**Comment by Schykle** [comment]
**Adding a note here for anyone else that might be struggling with this currently:** As a workaround, I was able to install `systemsettings`, the KDE System Settings application, and from there it seems that I can disable the function that allows applications to block compositing. This is, however, just a workaround, and it is potentially dangerous to use tools like this to change advanced settings in other desktops, as variations in implementation could render a desktop entirely unusable.
![image](https://user-images.githubusercontent.com/58709504/98131916-06451980-1e79-11eb-9e12-8bd1d6660661.png)

**Comment by openarun** [comment]
I am closing this bug as I believe the latest release of UbuntuDDE has this issue fixed. If you find this bug in the latest releases, please feel free to re-open and mention your UbuntuDDE Remix version.
