### ISSUE TITLE
Login Screen Issue - Black Screen After Boot

### ISSUE THREAD

**Issue by zamostny** [UbuntuDDE/bugs#35]
UDDE 20.10, black screen few seconds after log in screen is displayed. 
Able to reproduce 100% 

Previous users note holding ESC key will cause a command line login window to appear but then return to the graphical login screen. This does work as a workaround but timing is key to make it work.

Note, this is one a Lenovo L490 laptop with two other OS's installed. Using Grub from UDDE with "theme" enabled. Have not tried without theme.

**Comment by openarun** [comment]
dupe of #11

**Comment by openarun** [comment]
I am closing this bug as I believe the latest release of UbuntuDDE has this issue fixed. If you find this bug in the latest releases, please feel free to re-open and mention your UbuntuDDE Remix version.
