### ISSUE TITLE
Shutting down UbuntuDDE 20.10 always gives 'Unattended Upgrades Shutdown' error

### ISSUE THREAD

**Issue by ddebob6** [UbuntuDDE/bugs#37]
As per the title, when shutting down UbuntuDDE 20.10 I always get an 'Unattended Upgrades Shutdown' error. It then goes on to say 'Stop ongoing upgrades or perform upgrades before shutdown. The programs are preventing the computer from shutting down' and I have to click OK to proceed. It's been doing this since I first installed 20.10, even when I have no upgrades to install. Other people have mentioned this error on Reddit but it wasn't listed here until now.

**Comment by serial02** [comment]
Here the same thing happened and to resolve this momentarily I removed it with:

sudo apt remove unattended-upgrades

@openarun
