### ISSUE TITLE
Date format shown in tray is incorrect for United Kingdom (UbuntuDDE 20.10)

### ISSUE THREAD

**Issue by ddebob6** [UbuntuDDE/bugs#38]
Although I selected United Kingdom during install for my location, the tray still displays the date format as year/month/day when it should be day/month/year. I can't even change it from 'Time Settings' as there is no option under Short Date to select the UK format.

**Comment by ghost** [comment]
+1 same problem here in France.
Normal Date DD/MM/YYY, installation done  in French.
Date in dock still YYY/MM/DD, no option avalaible in settings.

**Comment by openarun** [comment]
dupe of #17
