### ISSUE TITLE
Dock disappers suddenly

### ISSUE THREAD

**Issue by Pravesh45** [UbuntuDDE/bugs#4]
**Describe the bug**
The dock in ubuntuDDE disappers suddenly.I don't think any particular thing is triggering this issue.it can only be brought back by rebooting. 

**Screenshots**
[https://photos.app.goo.gl/BgVJaNSGMPwG9Wk2A](url)

**Desktop (please complete the following information):**
OS: Ubuntu 20.04.1 LTS x86_64
Host: 81H7 Lenovo ideapad 130-15IKB
Kernel: 5.4.0-42-generic
WM: Mutter(DeepinGala)
CPU: Intel i5-8250U (8) @ 3.400GHz
GPU: NVIDIA GeForce MX110
GPU: Intel UHD Graphics 620
Memory: 6290MiB / 7826MiB

**Comment by anantamishra** [comment]
Hey @Pravesh45  we have kwin as default windows manager in UbuntuDDE and the bug you described earlier is not present in kwin so, do check it once and leave a comment here:

Command to be executed to switch kwin as windows manager:
`sudo apt remove deepin-wm && sudo apt install dde-kwin`

**Comment by Pravesh45** [comment]
But I was on dde-kwin before but then switched to deepin-wm because of the black border issue.As far as I know it isn't fixed yet right??

**Comment by anantamishra** [comment]
As of my experience the issue seems ot be solved now, please update your system to the latest release of UbuntuDDE i.e. UbuntuDDE 20.04.1 release and check once
