### ISSUE TITLE
Nextcloud issue

### ISSUE THREAD

**Issue by ghost** [UbuntuDDE/bugs#40]
Hi
I'm using UDDE 20.10. on a fresh new installation.
I have an issue with Nextcloud sync client.

**Normal Behaviour :** 
1/ On the first launch of nextcloud i set my account for the sync with my external server.
2/ when the app is connected to the server, the app dissappear (no app on the dock) and go to the systray (background use)
3/ I can open the app to change settings, look for document conflict... by clicking on the systray icon.

**My behaviour on UDDE :**
1/ Ok normal behaviour
2/ The app dissappear but no systray icon to open in the futur.
3/ The app works properly on background but i have no way to control that the sync works great or if there is conflict.

**How to reproduce :**
1/ Install Nextcloud Sync Client
2/ Connect to a server.

Lest me know if you need more info, log....

**Comment by scroom** [comment]
Same here. If some more info needed, please let me know

**Comment by scroom** [comment]
Seems to have been fixed with the latest update. @ghost Can you confirm this?

**Comment by openarun** [comment]
I am closing this bug because groovy is EOL and I believe the latest release of UbuntuDDE has this issue fixed. If you find this bug in the latest releases, please feel free to re-open and mention your UbuntuDDE Remix version.
