### ISSUE TITLE
Below is a report of some adjustments that need to be made in Ubuntu-DDE

### ISSUE THREAD

**Issue by serial02** [UbuntuDDE/bugs#41]
Hello Ubuntu-DDE Team

Below is a report of some adjustments that need to be made in Ubuntu-DDE
https://pastebin.com/UhtUhE26

``sudo journalctl -p 3 -xb
[sudo] senha para edson: 
-- Logs begin at Thu 2020-11-12 20:44:14 -03, end at Sun 2020-11-15 10:29:21 -03. --
nov 15 08:10:23 edson-p6540br kernel: usb 1-1.6: 3:1: cannot get freq at ep 0x84
nov 15 08:10:28 edson-p6540br thermald[3747]: THD engine start failed
nov 15 08:10:29 edson-p6540br smartd[3746]: Device: /dev/sda [SAT], 1 Currently unreadable (pending) sectors
nov 15 08:10:41 edson-p6540br lightdm[6431]: PAM unable to dlopen(pam_kwallet.so): /lib/security/pam_kwallet.so:>
nov 15 08:10:41 edson-p6540br lightdm[6431]: PAM adding faulty module: pam_kwallet.so
nov 15 08:10:41 edson-p6540br lightdm[6431]: PAM unable to dlopen(pam_kwallet5.so): /lib/security/pam_kwallet5.s>
nov 15 08:10:41 edson-p6540br lightdm[6431]: PAM adding faulty module: pam_kwallet5.so
nov 15 08:10:41 edson-p6540br lightdm[6431]: PAM unable to dlopen(pam_deepin_auth.so): /lib/security/pam_deepin_>
nov 15 08:10:41 edson-p6540br lightdm[6431]: PAM adding faulty module: pam_deepin_auth.so
nov 15 08:10:44 edson-p6540br kernel: usb 1-1.6: 3:1: cannot get freq at ep 0x84
nov 15 08:10:44 edson-p6540br kernel: usb 1-1.6: 3:1: cannot get freq at ep 0x84
nov 15 08:10:45 edson-p6540br esets_mac[6486]: error[19560000]: Não é possível desbloquear a mídia removível (or>
nov 15 08:10:47 edson-p6540br lightdm[6550]: PAM unable to dlopen(pam_kwallet.so): /lib/security/pam_kwallet.so:>
nov 15 08:10:47 edson-p6540br lightdm[6550]: PAM adding faulty module: pam_kwallet.so
nov 15 08:10:47 edson-p6540br lightdm[6550]: PAM unable to dlopen(pam_kwallet5.so): /lib/security/pam_kwallet5.s>
nov 15 08:10:47 edson-p6540br lightdm[6550]: PAM adding faulty module: pam_kwallet5.so
nov 15 08:10:47 edson-p6540br lightdm[6550]: PAM unable to dlopen(pam_deepin_auth.so): /lib/security/pam_deepin_>
nov 15 08:10:47 edson-p6540br lightdm[6550]: PAM adding faulty module: pam_deepin_auth.so
nov 15 08:10:49 edson-p6540br lightdm[6580]: PAM unable to dlopen(pam_deepin_auth.so): /lib/security/pam_deepin_>
nov 15 08:10:49 edson-p6540br lightdm[6580]: PAM adding faulty module: pam_deepin_auth.so
lines 1-21...skipping...
-- Logs begin at Thu 2020-11-12 20:44:14 -03, end at Sun 2020-11-15 10:29:21 -03. --                                                                                      
nov 15 08:10:23 edson-p6540br kernel: usb 1-1.6: 3:1: cannot get freq at ep 0x84                                                                                          
nov 15 08:10:28 edson-p6540br thermald[3747]: THD engine start failed                                                                                                     
nov 15 08:10:29 edson-p6540br smartd[3746]: Device: /dev/sda [SAT], 1 Currently unreadable (pending) sectors                                                              
nov 15 08:10:41 edson-p6540br lightdm[6431]: PAM unable to dlopen(pam_kwallet.so): /lib/security/pam_kwallet.so: cannot open shared object file: No such file or directory
nov 15 08:10:41 edson-p6540br lightdm[6431]: PAM adding faulty module: pam_kwallet.so                                                                                     
nov 15 08:10:41 edson-p6540br lightdm[6431]: PAM unable to dlopen(pam_kwallet5.so): /lib/security/pam_kwallet5.so: cannot open shared object file: No such file or direct>
nov 15 08:10:41 edson-p6540br lightdm[6431]: PAM adding faulty module: pam_kwallet5.so                                                                                    
nov 15 08:10:41 edson-p6540br lightdm[6431]: PAM unable to dlopen(pam_deepin_auth.so): /lib/security/pam_deepin_auth.so: cannot open shared object file: No such file or >
nov 15 08:10:41 edson-p6540br lightdm[6431]: PAM adding faulty module: pam_deepin_auth.so                                                                                 
nov 15 08:10:44 edson-p6540br kernel: usb 1-1.6: 3:1: cannot get freq at ep 0x84                                                                                          
nov 15 08:10:44 edson-p6540br kernel: usb 1-1.6: 3:1: cannot get freq at ep 0x84                                                                                          
nov 15 08:10:45 edson-p6540br esets_mac[6486]: error[19560000]: Não é possível desbloquear a mídia removível (org.freedesktop.udisks2.filesystem-mount)                   
nov 15 08:10:47 edson-p6540br lightdm[6550]: PAM unable to dlopen(pam_kwallet.so): /lib/security/pam_kwallet.so: cannot open shared object file: No such file or directory
nov 15 08:10:47 edson-p6540br lightdm[6550]: PAM adding faulty module: pam_kwallet.so                                                                                     
nov 15 08:10:47 edson-p6540br lightdm[6550]: PAM unable to dlopen(pam_kwallet5.so): /lib/security/pam_kwallet5.so: cannot open shared object file: No such file or direct>
nov 15 08:10:47 edson-p6540br lightdm[6550]: PAM adding faulty module: pam_kwallet5.so                                                                                    
nov 15 08:10:47 edson-p6540br lightdm[6550]: PAM unable to dlopen(pam_deepin_auth.so): /lib/security/pam_deepin_auth.so: cannot open shared object file: No such file or >
nov 15 08:10:47 edson-p6540br lightdm[6550]: PAM adding faulty module: pam_deepin_auth.so
nov 15 08:10:49 edson-p6540br lightdm[6580]: PAM unable to dlopen(pam_deepin_auth.so): /lib/security/pam_deepin_auth.so: cannot open shared object file: No such file or >
nov 15 08:10:49 edson-p6540br lightdm[6580]: PAM adding faulty module: pam_deepin_auth.so
nov 15 08:10:49 edson-p6540br lightdm[6580]: PAM unable to dlopen(pam_kwallet.so): /lib/security/pam_kwallet.so: cannot open shared object file: No such file or directory
nov 15 08:10:49 edson-p6540br lightdm[6580]: PAM adding faulty module: pam_kwallet.so
nov 15 08:10:49 edson-p6540br lightdm[6580]: PAM unable to dlopen(pam_kwallet5.so): /lib/security/pam_kwallet5.so: cannot open shared object file: No such file or direct>
nov 15 08:10:49 edson-p6540br lightdm[6580]: PAM adding faulty module: pam_kwallet5.so
nov 15 08:10:55 edson-p6540br lightdm[6580]: gkr-pam: unable to locate daemon control file
nov 15 08:11:10 edson-p6540br pulseaudio[6646]: GetManagedObjects() failed: org.freedesktop.DBus.Error.TimedOut: Failed to activate service 'org.bluez': timed out (servi>
nov 15 08:11:56 edson-p6540br sudo[11444]: PAM unable to dlopen(pam_deepin_auth.so): /lib/security/pam_deepin_auth.so: não é possível abrir arquivo compartilhado: Arquiv>
nov 15 08:11:56 edson-p6540br sudo[11444]: PAM adding faulty module: pam_deepin_auth.so
nov 15 08:12:06 edson-p6540br daemon/bluetooth[8526]: bluetooth.go:382: Failed to activate service 'org.bluez': timed out (service_start_timeout=25000ms)
                                                        ->  bluetooth.go:352
                                                        ->  asm_amd64.s:1373
nov 15 08:12:06 edson-p6540br daemon/bluetooth[8526]: obex_agent.go:103: failed to register obex agent: The name org.bluez.obex was not provided by any .service files
                                                        ->  obex_agent.go:93
                                                        ->  bluetooth.go:354
                                                        ->  asm_amd64.s:1373
nov 15 08:12:30 edson-p6540br sudo[14896]: PAM unable to dlopen(pam_deepin_auth.so): /lib/security/pam_deepin_auth.so: não é possível abrir arquivo compartilhado: Arquiv>
nov 15 08:12:30 edson-p6540br sudo[14896]: PAM adding faulty module: pam_deepin_auth.so
nov 15 08:12:38 edson-p6540br sudo[14897]: PAM unable to dlopen(pam_deepin_auth.so): /lib/security/pam_deepin_auth.so: não é possível abrir arquivo compartilhado: Arquiv>
nov 15 08:12:38 edson-p6540br sudo[14897]: PAM adding faulty module: pam_deepin_auth.so
nov 15 08:12:52 edson-p6540br sudo[16203]: PAM unable to dlopen(pam_deepin_auth.so): /lib/security/pam_deepin_auth.so: não é possível abrir arquivo compartilhado: Arquiv>
nov 15 08:12:52 edson-p6540br sudo[16203]: PAM adding faulty module: pam_deepin_auth.so
nov 15 08:13:06 edson-p6540br sudo[16207]: PAM unable to dlopen(pam_deepin_auth.so): /lib/security/pam_deepin_auth.so: não é possível abrir arquivo compartilhado: Arquiv>
nov 15 08:13:06 edson-p6540br sudo[16207]: PAM adding faulty module: pam_deepin_auth.so
nov 15 08:13:13 edson-p6540br sudo[17511]: PAM unable to dlopen(pam_deepin_auth.so): /lib/security/pam_deepin_auth.so: não é possível abrir arquivo compartilhado: Arquiv>
nov 15 08:13:13 edson-p6540br sudo[17511]: PAM adding faulty module: pam_deepin_auth.so
nov 15 08:17:01 edson-p6540br CRON[33267]: PAM unable to dlopen(pam_deepin_auth.so): /lib/security/pam_deepin_auth.so: não é possível abrir arquivo compartilhado: Arquiv>
nov 15 08:17:01 edson-p6540br CRON[33267]: PAM adding faulty module: pam_deepin_auth.so
nov 15 08:30:01 edson-p6540br CRON[80141]: PAM unable to dlopen(pam_deepin_auth.so): /lib/security/pam_deepin_auth.so: não é possível abrir arquivo compartilhado: Arquiv>
nov 15 08:30:01 edson-p6540br CRON[80141]: PAM adding faulty module: pam_deepin_auth.so
nov 15 08:40:31 edson-p6540br smartd[3746]: Device: /dev/sda [SAT], 1 Currently unreadable (pending) sectors
nov 15 09:10:31 edson-p6540br smartd[3746]: Device: /dev/sda [SAT], 1 Currently unreadable (pending) sectors
nov 15 09:17:01 edson-p6540br CRON[95294]: PAM unable to dlopen(pam_deepin_auth.so): /lib/security/pam_deepin_auth.so: não é possível abrir arquivo compartilhado: Arquiv>
nov 15 09:17:01 edson-p6540br CRON[95294]: PAM adding faulty module: pam_deepin_auth.so
nov 15 09:30:01 edson-p6540br CRON[95903]: PAM unable to dlopen(pam_deepin_auth.so): /lib/security/pam_deepin_auth.so: não é possível abrir arquivo compartilhado: Arquiv>
nov 15 09:30:01 edson-p6540br CRON[95903]: PAM adding faulty module: pam_deepin_auth.so
nov 15 09:40:31 edson-p6540br smartd[3746]: Device: /dev/sda [SAT], 1 Currently unreadable (pending) sectors
nov 15 09:43:16 edson-p6540br deepin-turbo-invoker[96642]: error: Failed to initiate connect on the socket for type dtkwidget.
nov 15 09:43:16 edson-p6540br deepin-turbo-invoker[96642]: error: Failed to initiate connect on the socket for type generic.
nov 15 09:43:16 edson-p6540br deepin-turbo-invoker[96642]: error: Start application /usr/bin/deepin-screen-recorder as a binary executable without launcher...
nov 15 10:10:31 edson-p6540br smartd[3746]: Device: /dev/sda [SAT], 1 Currently unreadable (pending) sectors
nov 15 10:12:27 edson-p6540br sudo[98750]: PAM unable to dlopen(pam_deepin_auth.so): /lib/security/pam_deepin_auth.so: não é possível abrir arquivo compartilhado: Arquiv>
nov 15 10:12:27 edson-p6540br sudo[98750]: PAM adding faulty module: pam_deepin_auth.so
nov 15 10:13:27 edson-p6540br sudo[99563]: PAM unable to dlopen(pam_deepin_auth.so): /lib/security/pam_deepin_auth.so: não é possível abrir arquivo compartilhado: Arquiv>
nov 15 10:13:27 edson-p6540br sudo[99563]: PAM adding faulty module: pam_deepin_auth.so
nov 15 10:13:36 edson-p6540br sudo[99576]: PAM unable to dlopen(pam_deepin_auth.so): /lib/security/pam_deepin_auth.so: não é possível abrir arquivo compartilhado: Arquiv>
nov 15 10:13:36 edson-p6540br sudo[99576]: PAM adding faulty module: pam_deepin_auth.so
nov 15 10:17:01 edson-p6540br CRON[99699]: PAM unable to dlopen(pam_deepin_auth.so): /lib/security/pam_deepin_auth.so: não é possível abrir arquivo compartilhado: Arquiv>
nov 15 10:17:01 edson-p6540br CRON[99699]: PAM adding faulty module: pam_deepin_auth.so
nov 15 10:29:16 edson-p6540br sudo[100339]: PAM unable to dlopen(pam_deepin_auth.so): /lib/security/pam_deepin_auth.so: não é possível abrir arquivo compartilhado: Arqui>
nov 15 10:29:16 edson-p6540br sudo[100339]: PAM adding faulty module: pam_deepin_auth.so
lines 33-71/71 (END)

**Comment by openarun** [comment]
I am closing this bug as I believe the latest release of UbuntuDDE has this issue fixed. If you find this bug in the latest releases, please feel free to re-open and mention your UbuntuDDE Remix version.
