### ISSUE TITLE
Ubuntu-DDE doesn't have a Brazilian Portuguese language?

### ISSUE THREAD

**Issue by serial02** [UbuntuDDE/bugs#42]
Hello Ubuntu-DDE Team

There is a language for GOD and the world, except Brazilian Portuguese - PT BR 

https://imgur.com/bgFhnTN

There is a lot of text mixed with Portuguese from Portugal and English. What about Brazilian Portuguese?

![Screen Capture_20201115111955](https://user-images.githubusercontent.com/32621790/99187350-f5c45700-2734-11eb-8b8d-a37c8dc0182e.png)

**Comment by serial02** [comment]
@openarun

**Comment by openarun** [comment]
I am closing this bug as I believe the latest release of UbuntuDDE has this issue fixed. If you find this bug in the latest releases, please feel free to re-open and mention your UbuntuDDE Remix version.
