### ISSUE TITLE
You are not allowed to operate file / folder!

### ISSUE THREAD

**Issue by serial02** [UbuntuDDE/bugs#43]
Hello Ubuntu-DDE Team

When saving an image to the desktop and deleting it, the following error message appears:

You are not allowed to operate file / folder!

Note: The file is deleted, but the message that appears is an error.

**Comment by ddebob6** [comment]
Confirming this bug. File is removed but shows error message: You do not have permission to operate file/folder!

**Comment by openarun** [comment]
I am closing this bug because groovy is EOL and I believe the latest release of UbuntuDDE has this issue fixed. If you find this bug in the latest releases, please feel free to re-open and mention your UbuntuDDE Remix version.
