### ISSUE TITLE
Dmesg report showing some errors, conflicts and blockages of hardware, applications and software

### ISSUE THREAD

**Issue by serial02** [UbuntuDDE/bugs#44]
Hello Ubuntu-DDE Team

The following is a Dmesg report showing some errors, conflicts and blockages in hardware, applications and software. Some new and old bugs already known.

https://pastebin.com/nNcTDiBF

Errors already known:

https://bugs.launchpad.net/ubuntu/+source/apparmor/+bug/1571531
https://plus.diolinux.com.br/t/mensagens-de-erro-no-eset-4-0-90-para-linux/929/9
https://forum.eset.com/topic/16859-cannot-connect-to-tmpesetssockpermission-denied/
https://forum.eset.com/topic/17459-error-messages-log-files-mensagens-de-erro-arquivos-de-log/?tab=comments#comment-86490

Following images:
https://imgur.com/vU3DdEm

**Comment by serial02** [comment]
@openarun

**Comment by openarun** [comment]
I am closing this bug because groovy is EOL and I believe the latest release of UbuntuDDE has this issue fixed. If you find this bug in the latest releases, please feel free to re-open and mention your UbuntuDDE Remix version.
