### ISSUE TITLE
Notification Center does not appear in tray in UbuntuDDE 20.10

### ISSUE THREAD

**Issue by ddebob6** [UbuntuDDE/bugs#45]
Although the Notification Center is shown ticked as a default tray plugin, it doesn't actually appear (or at least not on my system). You can make it appear by un-ticking and then re-ticking the entry in Plugins, but the tray icon is shown only in black and disappears again when you reboot.

**Comment by anantamishra** [comment]
DUP of #20

**Comment by anantamishra** [comment]
Duplicate of #20
