### ISSUE TITLE
update-notifier package

### ISSUE THREAD

**Issue by serial02** [UbuntuDDE/bugs#46]
Hello Ubuntu-DDE 20.10 Team

Every new boot appears the same error message in Ubuntu-DDE 20.10, but we are unable to view the error report presented

![Screen Capture_20201116090148](https://user-images.githubusercontent.com/32621790/99251079-7ba2d980-27eb-11eb-80cf-bd18952a9340.png)

https://bugs.launchpad.net/ubuntu/+source/update-notifier/+bug/1904401

**Comment by openarun** [comment]
You can click on cancel if there are such prompts for now. And if you get any sort of crash reports or any issue you can always update in our bug tracker here than in bugs.launchapd.net.
Thanks!

**Comment by serial02** [comment]
> You can click on cancel if there are such prompts for now. And if you get any sort of crash reports or any issue you can always update in our bug tracker here than in bugs.launchapd.net.
> Thanks!

@openarun 
There is a question in all this:
We send error reports at every startup by choice and gladly, but in return you do not allow us to see what is being sent? Can you create this option? The greater the transparency, the greater the reliability.

**Comment by serial02** [comment]
Hello @openarun 

I believe that you must have understood what we talked about on Telegram. If possible, open the topic so that the changes and suggestions sent can happen.

**Comment by serial02** [comment]
@openarun 

Thank You

**Comment by serial02** [comment]
Suggestion:  

In my opinion this is an option only for Ubuntu, where when clicking send report the information is sent through the registered email to the Canonical website, where they will see all the content and, after analyzing it, check the necessary measures to correct the error or inconsistency presented for a possible correction.  

As this function does not work on Ubuntu-DDE 20.10 and does not send anything at the moment, they could do something similar to Ubuntu, where through registered email and password created by the user so that the relevant information can be sent to Github Ubuntu/Bugs automatically, sending the maximum possible information about the Distro in use and its possible irregularities.

@openarun

**Comment by serial02** [comment]
Hello

Another excellent option would be to add the Deepin V20 1003 log viewer to Ubuntu-DDE 20.10, but first you need to make it work and export the requested logs. With the information being sent in real time to the Ubuntu-DDE team there would be a facilitation for solving and correcting inconsistencies and errors if they exist.

![Captura de Tela_deepin-log-viewer_20201127104608](https://user-images.githubusercontent.com/32621790/100455798-18902d00-309e-11eb-9ed4-45722b73fe1e.png)

@openarun

**Comment by openarun** [comment]
I am closing this bug because groovy is EOL and I believe the latest release of UbuntuDDE has this issue fixed. If you find this bug in the latest releases, please feel free to re-open and mention your UbuntuDDE Remix version.
