### ISSUE TITLE
Follows error reports for analysis and solution of some applications in Ubuntu DDE 20.10

### ISSUE THREAD

**Issue by serial02** [UbuntuDDE/bugs#48]
Hello Ubuntu DDE 20.10 Team

Follows error reports for analysis and solution of some applications in Ubuntu DDE 20.10

[_usr_bin_byzanz-record.1000.zip](https://github.com/UbuntuDDE/bugs/files/5560242/_usr_bin_byzanz-record.1000.zip)

[_usr_bin_deepin-anything-tool.0.zip](https://drive.google.com/file/d/1SmkxbwEwYA3lTvXBX5TvDnzyZOt2YkbM/view?usp=sharing)

[_usr_bin_deepin-screen-recorder.1000.zip](https://github.com/UbuntuDDE/bugs/files/5560256/_usr_bin_deepin-screen-recorder.1000.zip)

![Screen Capture_apport-gtk_20201118122559](https://user-images.githubusercontent.com/32621790/99550263-4936df00-2999-11eb-89ad-699ce2bbb4ea.png)

[_usr_bin_deepin-terminal.1000.zip](https://github.com/UbuntuDDE/bugs/files/5560263/_usr_bin_deepin-terminal.1000.zip)

[_usr_bin_stacer.1000.zip](https://github.com/UbuntuDDE/bugs/files/5560282/_usr_bin_stacer.1000.zip)

[_usr_lib_deepin-daemon_dde-osd.1000.zip](https://github.com/UbuntuDDE/bugs/files/5560357/_usr_lib_deepin-daemon_dde-osd.1000.zip)

[_usr_sbin_lightdm.0.zip](https://github.com/UbuntuDDE/bugs/files/5560298/_usr_sbin_lightdm.0.zip)

![Screen Capture_stacer_20201118094735](https://user-images.githubusercontent.com/32621790/99532484-25689e80-2983-11eb-8de6-d33425aa3723.png)

**Comment by serial02** [comment]
@openarun

**Comment by openarun** [comment]
These issues must have been resolved with the latest releases of the packages. If you still get any issues, feel free to open the bug and provide more specific logs.
Thanks!
