### ISSUE TITLE
Unable to uninstall application

### ISSUE THREAD

**Issue by haresh6x** [UbuntuDDE/bugs#5]
"Not able to uninstall application" when right click on specific application via start menu.

**Comment by anantamishra** [comment]
Hey @haresh6x , this feature doesn't seem to be synchronized yet, you can uninstall the any application from the Software Center

**Comment by openarun** [comment]
I am closing this bug because groovy is EOL and I believe the latest release of UbuntuDDE has this issue fixed. If you find this bug in the latest releases, please feel free to re-open and mention your UbuntuDDE Remix version.
