### ISSUE TITLE
Yutube-DL and Youtube-DLG updated version is available?

### ISSUE THREAD

**Issue by serial02** [UbuntuDDE/bugs#50]
Hello Ubuntu-DDE Team 20.10

Would you know when to have the updated version of Youtube-dl updated and corrected? According to information it is available again. The version that is available in Ubuntu-DDE has an error message and is out of date, as follows:

```
youtube-dl https://www.youtube.com/watch?v=2btBefVKmQc
[youtube] 2btBefVKmQc: Downloading webpage
[youtube] 2btBefVKmQc: Downloading embed webpage
ERROR: Unable to extract JS player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

```
sudo apt install youtube-dl
[sudo] senha para edson: 
Lendo listas de pacotes... Pronto
Construindo árvore de dependências       
Lendo informação de estado... Pronto
youtube-dl is already the newest version (2020.09.14-1).
0 pacotes atualizados, 0 pacotes novos instalados, 0 a serem removidos e 0 não atualizados.
```

How much does Youtube-DLG have the possibility of making the updated version available in the Ubuntu-DDE repositories?

https://raw.githubusercontent.com/MrS0m30n3/youtube-dl-gui/gh-pages/images/ydlg_ui.gif 

Current version

![Screen Capture_select-area_20201118230616](https://user-images.githubusercontent.com/32621790/99611631-cfcbda80-29f2-11eb-8362-8783d3a58a4f.png)

**Comment by openarun** [comment]
We use the Ubuntu repository for youtube-dl and other upstream packages. And as Ubuntu doesn't have a rolling release scheme for releases, if you need the latest version, please try getting the package from the upstream.
