### ISSUE TITLE
execute application from filemanager in admin mode

### ISSUE THREAD

**Issue by HE-Andersson** [UbuntuDDE/bugs#51]
**Describe the bug**
When running the File Manager in administrator mode and also trying to use the File Manager to open some file or application either by clicking on an application directly or open a text, image, ... with right click icon: open with -> [application] the File Manager freezes / hangs... The rest of the desktop works. but not that File Manager window.

**To Reproduce**
1. Open File Manager
2. go to a directory with text or images
3. Right click an empty space in filemanager and select Open As Administrator
4. Select an image or Text by right click
5. menu: select open with -> appropriate application
4. See error: File Manager becomes frozen or hangs, further more you can't open a new File Manager window, navigate somewhere and choose "Open As Administrator" from that new window.

**Expected behavior**
Should open the file in administrator mode, for example /etc/fstab in a administration mode text editor

**Desktop (please complete the following information):**
UbuntuDDE Remix Groovy Gorilla - 20.10

**Comment by ddebob6** [comment]
Confirming this bug. It's the 'Open As Administrator' action that's crucial as I can't get the lock-up to happen any other way.

**Comment by HE-Andersson** [comment]
> Confirming this bug. It's the 'Open As Administrator' action that's crucial as I can't get the lock-up to happen any other way.

I tested another way, I opened the same filemanager from terminal with:

sudo dde-file-manager

then I navigated to

/usr/share/applications

right clicked on "File Manager".desktop application and selected "Open With" >> "Text Editor"

the file manager hanged / frooze as described initially but, this time I had a never ending rolling output in the terminal with the output beeing:

[date]:[time] - [debug  ] appcontroller.cpp    AppController::hasLaunchAppInterface 1393]  LaunchAppInterface is loading....

perhaps that will point someone to the right direction.?

**Comment by openarun** [comment]
I am closing this bug because groovy is EOL and I believe the latest release of UbuntuDDE has this issue fixed. If you find this bug in the latest releases, please feel free to re-open and mention your UbuntuDDE Remix version.
