### ISSUE TITLE
Journalctl -xe Ubuntu-DDE 20.10 em 23/11/202 as 12:59h

### ISSUE THREAD

**Issue by serial02** [UbuntuDDE/bugs#52]
Hello Ubuntu-DDE Team 20.10

After automatic updates this afternoon, a new report of inconsistencies found in ubuntu-DDE 20.10 follows

[Atualização Ubuntu-dde 23112020 as 1223h.txt](https://github.com/UbuntuDDE/bugs/files/5584275/Atualizacao.Ubuntu-dde.23112020.as.1223h.txt)

Journalctl -xe Ubuntu-DDE 23/11/2020 as 12:59h
https://pastebin.com/raw/diDmPKUR

@openarun

**Comment by openarun** [comment]
I am closing this bug because groovy is EOL and I believe the latest release of UbuntuDDE has this issue fixed. If you find this bug in the latest releases, please feel free to re-open and mention your UbuntuDDE Remix version.
