### ISSUE TITLE
Journalctl -xe Ubuntu-DDE 20.10 23112020 as 14:00h

### ISSUE THREAD

**Issue by serial02** [UbuntuDDE/bugs#53]
Hello Ubuntu-DDE Team 20.10

After this afternoon's second update, a new report of inconsistencies found follows, as follows:

[Atualização Ubuntu-DDE 23112020 as 1403h.txt](https://github.com/UbuntuDDE/bugs/files/5584657/Atualizacao.Ubuntu-DDE.23112020.as.1403h.txt)

Following report Journalctl -xe Ubuntu-DDE 2311202 as 14:00h
https://pastebin.com/jFy7iK8i
https://pastebin.com/raw/jFy7iK8i

@openarun

**Comment by openarun** [comment]
I am closing this bug because groovy is EOL and I believe the latest release of UbuntuDDE has this issue fixed. If you find this bug in the latest releases, please feel free to re-open and mention your UbuntuDDE Remix version.
