### ISSUE TITLE
Journalctl -xe Ubuntu-DDE 20.10 em 24/11/2020 as 22:00h

### ISSUE THREAD

**Issue by serial02** [UbuntuDDE/bugs#54]
Hello Ubuntu-DDE Team 20.10

Daily update of Ubuntu-DDE on 24/11/2020 at 21: 40h successfully. Following is the application update report.
[Atualização Ubuntu-DDE 20.10 em 24112020 as 2140h.txt](https://github.com/UbuntuDDE/bugs/files/5593716/Atualizacao.Ubuntu-DDE.20.10.em.24112020.as.2140h.txt)

After a late night update on 11/24/2020 at 9:40 pm, a new report of inconsistencies found in Journalctl -xe follows.
https://pastebin.com/xk5bXfU5
https://pastebin.com/raw/xk5bXfU5

@openarun

**Comment by openarun** [comment]
I am closing this bug because groovy is EOL and I believe the latest release of UbuntuDDE has this issue fixed. If you find this bug in the latest releases, please feel free to re-open and mention your UbuntuDDE Remix version.
