### ISSUE TITLE
Ubuntu-DDE 20.10 boot screen sometimes crashes

### ISSUE THREAD

**Issue by serial02** [UbuntuDDE/bugs#56]
Hello Ubuntu-DDE Team 20.10

When restarting the machine and choosing another Distro option, the Ubuntu-DDE 20.10 Boot screen sometimes freezes and it is only possible to restart by turning off the Desktop on the (OFF) button.

![WhatsApp Image 2020-11-25 at 13 17 47](https://user-images.githubusercontent.com/32621790/100255301-1bfea980-2f22-11eb-9209-3cb6f355efa2.jpeg)

**Comment by openarun** [comment]
I am closing this bug because groovy is EOL and I believe the latest release of UbuntuDDE has this issue fixed. If you find this bug in the latest releases, please feel free to re-open and mention your UbuntuDDE Remix version.
