### ISSUE TITLE
[Solved] We request the inclusion of deepin-draw_5.8.0.81-1_amd64.deb in the daily updates of Ubuntu-DDE 20.10

### ISSUE THREAD

**Issue by serial02** [UbuntuDDE/bugs#58]
Hello Ubuntu-DDE Team 20.10

We request the inclusion of the deepin-draw_5.8.0.81-1_amd64.deb package in the daily updates of Ubuntu-DDE 20.10.
Note: The package cannot be installed manually due to dependency errors. Attempting to install the dependencies generates other conflicts due to the lack of update of some packages.

![Screen Capture_20201126181150](https://user-images.githubusercontent.com/32621790/100391894-ab37ba00-3013-11eb-8a42-acce9c1a4a2d.png)

@openarun

**Comment by serial02** [comment]
Hello Ubuntu-DDE  20.10 Team

Deepin-draw application available and successfully installed. Thank you!

sudo apt install deepin-draw

![Screen Capture_deepin-draw_20201208212624](https://user-images.githubusercontent.com/32621790/101557750-60fff280-399c-11eb-99d9-3795ac40f1c4.png)

@openarun 
@anantamishra

**Comment by openarun** [comment]
The package deepin-draw is uploaded to the UbuntuDDE Remix 20.10 groovy repository :)
Cheers!
