### ISSUE TITLE
We request the inclusion of deepin-camera_1.0.0.15-1_amd64 in Ubuntu-DDE 20.10

### ISSUE THREAD

**Issue by serial02** [UbuntuDDE/bugs#59]
Hello Ubuntu-DDE Team 20.10  

We request the inclusion of the deepin-camera_1.0.0.15-1_amd64 package in Ubuntu-DDE 20.10.  

Note: When trying to install the application manually, it requires the removal of two plugins and the installation of two others. Afraid to update and generate some conflict I did not perform the installation manually.  

Note: I used the Ubuntu application, the Gdebi Package Installer and, in the installation attempt it shows the options for removing and installing the packages. This package (Gdebi Package Installer) in my opinion needs correction, as it expands a lot but does not show the four files at the same time. There is a lot of wasted space. Viewing all packages could be instantaneous.

![Screen Capture_dde-file-manager_20201126182414](https://user-images.githubusercontent.com/32621790/100392470-6a40a500-3015-11eb-8797-45e85677335d.png)

@openarun

**Comment by openarun** [comment]
Hey @serial02 , 
Deepin Camera is not free and open source yet and the source code is still not available in the repository: https://github.com/linuxdeepin/deepin-camera .
Once it's available, we'll be including it in our repository.

**Comment by serial02** [comment]
> Hey @serial02 ,
> Deepin Camera is not free and open source yet and the source code is still not available in the repository: https://github.com/linuxdeepin/deepin-camera .
> Once it's available, we'll be including it in our repository.

Hello @openarun 

Thanks for the feedback

**Comment by openarun** [comment]
I am closing this bug because groovy is EOL and I believe the latest release of UbuntuDDE has this issue fixed. If you find this bug in the latest releases, please feel free to re-open and mention your UbuntuDDE Remix version.
