### ISSUE TITLE
Check the possibility of including the LOG Viewer from Deepin V20 1003 to Ubuntu-DDE 20.10

### ISSUE THREAD

**Issue by serial02** [UbuntuDDE/bugs#62]
Hello

Another excellent option would be to add the Deepin V20 1003 log viewer to Ubuntu-DDE 20.10, but first you need to make it work and export the requested logs. With the information being sent in real time to the Ubuntu-DDE team there would be a facilitation for solving and correcting inconsistencies and errors if they exist.

![Captura de Tela_deepin-log-viewer_20201127104608](https://user-images.githubusercontent.com/32621790/100456172-b257da00-309e-11eb-9a3e-2eb2f859654d.png)

@openarun

**Comment by anantamishra** [comment]
The package is now available in the stable repo of UbuntuDDE 
You can now install the  package using the following command:
```
sudo apt install deepin-log-viewer

**Comment by serial02** [comment]
> The package is now available in the stable repo of UbuntuDDE
> You can now install the package using the following command:
> 
> ```
> sudo apt install deepin-log-viewer
> ```

Hello @anantamishra 

Deepin-log-viewer successfully installed (!) Thank you very much! I find this tool very useful, but it has the same problem as in the Deepin V20 1003.

Following images:

![Screen Capture_deepin-terminal_20201208083609](https://user-images.githubusercontent.com/32621790/101480574-9ff95e00-3932-11eb-9ab6-46d50b7aa3de.png)

![Screen Capture_deepin-log-viewer_20201208083942](https://user-images.githubusercontent.com/32621790/101480607-af78a700-3932-11eb-945f-8948e40af983.png)

At the moment, the application does not export and does not save the selected logs that we want and can we not open the files for reading and analysis? Do they happen to be in a folder by default?

![Screen Capture_deepin-log-viewer_20201208084430](https://user-images.githubusercontent.com/32621790/101480669-c6b79480-3932-11eb-8ef7-1a7ec93f9b0c.png)


![Screen Capture_deepin-log-viewer_20201208084528](https://user-images.githubusercontent.com/32621790/101480690-cd460c00-3932-11eb-9739-c118f5f3c723.png)

The left side does not expand, not showing the full names of the titles.

![Screen Capture_deepin-log-viewer_20201208085406](https://user-images.githubusercontent.com/32621790/101480845-fd8daa80-3932-11eb-85e1-291602f5ba0f.png)

If necessary, keep the topic open until this problem is solved.

@openarun 
@anantamishra

**Comment by openarun** [comment]
I am closing this bug because groovy is EOL and I believe the latest release of UbuntuDDE has this issue fixed. If you find this bug in the latest releases, please feel free to re-open and mention your UbuntuDDE Remix version.
