### ISSUE TITLE
Ubuntu-DDE 20.10 presented an internal error, being: _usr_libexec_at-spi2-registryd.1000

### ISSUE THREAD

**Issue by serial02** [UbuntuDDE/bugs#63]
Hello Ubuntu-DDE Team 20.10

After the login screen and starting the desktop screen, these images appeared with the following message:

![Screen Capture_20201128032956](https://user-images.githubusercontent.com/32621790/100495628-1ffe1780-312c-11eb-977b-eb8d7656a5f1.png)

As I know this is a standard Canonical Ubuntu procedure, I clicked send, but the content was not sent, as I was not redirected to the Ubuntu / Bugs canonical site to complete sending the bug report, so I'm adding the report here error submitted for analysis and action

![Screen Capture_20201128033044](https://user-images.githubusercontent.com/32621790/100495706-eb3e9000-312c-11eb-8fd8-3f1a723e6477.png)

When opening Stacer, the logs generated were as follows:

Ubuntu-DDE 20.10 error /usr/libexec/at-spi2-registryd.1000.crash
https://pastebin.com/8k7Xzskz
https://pastebin.com/raw/8k7Xzskz

[_usr_libexec_at-spi2-registryd.1000.zip](https://github.com/UbuntuDDE/bugs/files/5610171/_usr_libexec_at-spi2-registryd.1000.zip)
[_usr_libexec_at-spi2-registryd.1000.upload.zip](https://github.com/UbuntuDDE/bugs/files/5610172/_usr_libexec_at-spi2-registryd.1000.upload.zip)

Ubuntu-DDE 20.10 error _usr_bin_deepin-screen-recorder.1000.crash
[_usr_bin_deepin-screen-recorder.1000.zip](https://github.com/UbuntuDDE/bugs/files/5610168/_usr_bin_deepin-screen-recorder.1000.zip)

Ubuntu-DDE 20.10 error _usr_bin_deepin-deb-installer.1000.crash
[_usr_bin_deepin-deb-installer.1000.zip](https://github.com/UbuntuDDE/bugs/files/5610180/_usr_bin_deepin-deb-installer.1000.zip)

![Screen Capture_stacer_20201128033441](https://user-images.githubusercontent.com/32621790/100496077-e29b8900-312f-11eb-85a8-22fa81e96796.png)

@openarun

**Comment by openarun** [comment]
I am closing this bug because groovy is EOL and I believe the latest release of UbuntuDDE has this issue fixed. If you find this bug in the latest releases, please feel free to re-open and mention your UbuntuDDE Remix version.
