### ISSUE TITLE
Ubuntu-DDE presented an internal error being: _usr_bin_software-properties-gtk.1000.crash

### ISSUE THREAD

**Issue by serial02** [UbuntuDDE/bugs#66]
Hello Ubuntu-DDE 20.10 Team

Ubuntu-DDE presented an internal error being: _usr_bin_software-properties-gtk.1000.crash
The following is a report for analysis and measures:

https://pastebin.com/gQ6AcsA4
https://pastebin.com/raw/gQ6AcsA4

![Screen Capture_stacer_20201204150114](https://user-images.githubusercontent.com/32621790/101198006-937aba00-3641-11eb-9bf2-2e645613aa0a.png)

@openarun

**Comment by serial02** [comment]
I noticed on this date that the Software & update, as well as, the settings field in the Software Update no longer opens. After daily updates, the error must have worsened.

_usr_bin_software-properties-gtk.1000.crash
[_usr_bin_software-properties-gtk.1000.crash.zip](https://github.com/UbuntuDDE/bugs/files/5669419/_usr_bin_software-properties-gtk.1000.crash.zip)


![Screen Capture_dde-desktop_20201209204724](https://user-images.githubusercontent.com/32621790/101702926-9ff77c00-3a60-11eb-9909-d81d24e72e3a.gif)

**Comment by openarun** [comment]
I am closing this bug because groovy is EOL and I believe the latest release of UbuntuDDE has this issue fixed. If you find this bug in the latest releases, please feel free to re-open and mention your UbuntuDDE Remix version.
