### ISSUE TITLE
When restarting Ubuntu-DDE 20.10 it enters TTy mode and locks up

### ISSUE THREAD

**Issue by serial02** [UbuntuDDE/bugs#67]
Hello Deepin Team 20.10

When restarting Ubuntu-DDE 20.10 it enters TTy mode and locks up, being necessary to turn off the Desktop by the "shutdown" button. The strangest thing is to have entered TTy mode when restarting with a piece of text that you had typed on facebook.

Following images:

![a43739c5-a12f-454e-a4fa-6eb4e3eb55a4](https://user-images.githubusercontent.com/32621790/101414027-1ca12380-38c4-11eb-90c4-c169fadab4ab.jpeg)

![c1771d63-2197-4cd9-b661-5b14b44eb673](https://user-images.githubusercontent.com/32621790/101414042-21fe6e00-38c4-11eb-97c8-1203409cc2ed.jpeg)

Possible error message presented may have been sent in previous logs.

![Screen Capture_deepin-terminal_20201207193614](https://user-images.githubusercontent.com/32621790/101414145-4eb28580-38c4-11eb-9d59-da5d5d483300.png)

Here is a report of the moment of the problem:

```
dez 07 19:39:05 edson-p6540br agetty[13607]: tty1: invalid character 0x1b in login name
dez 07 19:39:53 edson-p6540br agetty[25047]: tty1: invalid character 0x16 in login name
dez 07 19:40:40 edson-p6540br agetty[26770]: tty1: invalid character 0x1b in login name
dez 07 19:42:10 edson-p6540br agetty[29381]: tty1: invalid character 0x1b in login name
dez 07 19:45:02 edson-p6540br agetty[32777]: tty1: invalid character 0x1b in login name
```

https://pastebin.com/sPNT9y0g

@openarun 

Edited: Within 10 days, errors and inconsistencies are almost the same:
Ubuntu-DDE 20.10 error journalctl -p 3 em 07/12/2020 as 20:45h
https://pastebin.com/1bDr3KCK
https://pastebin.com/raw/1bDr3KCK

**Comment by openarun** [comment]
I am closing this bug because groovy is EOL and I believe the latest release of UbuntuDDE has this issue fixed. If you find this bug in the latest releases, please feel free to re-open and mention your UbuntuDDE Remix version.
