### ISSUE TITLE
Critical error message in /dev/sda/ Ubuntu-DDE 20.10 is installed in /dev /sdb1

### ISSUE THREAD

**Issue by serial02** [UbuntuDDE/bugs#68]
Hello Ubuntu-DDE Team 20.10

Researching critical messages, I found the following information:
Critical error message in / dev /sda/ UbuntuDDE 20.10 is installed in /dev/sdb1.
It seems that the report on each boot does not complete?

![Screen Capture_gnome-disks_20201207215943](https://user-images.githubusercontent.com/32621790/101423775-94794900-38d8-11eb-934d-ce5db9814b86.png)

![Screen Capture_20201207220145](https://user-images.githubusercontent.com/32621790/101423785-99d69380-38d8-11eb-8a3e-a60f047136be.png)

```
dez 07 19:32:41 edson-p6540br smartd[2977]: Device: /dev/sda [SAT], 1 Currently unreadable (pending) sectors
dez 07 20:02:43 edson-p6540br smartd[2977]: Device: /dev/sda [SAT], 1 Currently unreadable (pending) sectors
dez 07 20:32:42 edson-p6540br smartd[2977]: Device: /dev/sda [SAT], 1 Currently unreadable (pending) sectors
dez 07 21:02:42 edson-p6540br smartd[2977]: Device: /dev/sda [SAT], 1 Currently unreadable (pending) sectors
dez 07 21:32:42 edson-p6540br smartd[2977]: Device: /dev/sda [SAT], 1 Currently unreadable (pending) sectors
```

Here is the full log:
Ubuntu-DDE 20.10 error journalctl -p 2 em 07/12/2020 as 22:12h
https://pastebin.com/SrXiGEzh
https://pastebin.com/raw/SrXiGEzh

@openarun

**Comment by openarun** [comment]
I am closing this bug because groovy is EOL and I believe the latest release of UbuntuDDE has this issue fixed. If you find this bug in the latest releases, please feel free to re-open and mention your UbuntuDDE Remix version.
