### ISSUE TITLE
freezing in multi tasking

### ISSUE THREAD

**Issue by SleepyOwL00** [UbuntuDDE/bugs#7]
while working with multiple application, when you select another app using the mouse the system freeze like this.
![DeepinScreenshot_dde-desktop_20200812174145](https://user-images.githubusercontent.com/64136026/90013565-21ade780-dcc3-11ea-9f4a-053ff4276059.png)
when you try to select another application, I am not able to do that and cannot work with that.

**Comment by anantamishra** [comment]
Can you please mention your device specification here along with the Winodows Manager being used in your system.

**Comment by anantamishra** [comment]
Please try upgrading your OS to the latest bulid i.e. UbuntuDDE 20.04.1 and check once because this issue seems to be solved in the latest build.

**Comment by openarun** [comment]
I am closing this bug as I believe the latest release of UbuntuDDE has this issue fixed. If you find this bug in the latest releases, please feel free to re-open and mention your UbuntuDDE Remix version.
