### ISSUE TITLE
After login, screen crashed and it was necessary to turn off the desktop button

### ISSUE THREAD

**Issue by serial02** [UbuntuDDE/bugs#70]
Hello Ubuntu -DDE 20.10 Team

After login, screen crashed and it was necessary to turn off the desktop button.
On the third try it worked again.
I believe that the logs already sent can help to identify this problem.
Note: In the center of the screen it is visible that the application has crashed and has not opened.

https://pastebin.com/u/SerialCom

![WhatsApp Image 2020-12-08 at 17 29 29](https://user-images.githubusercontent.com/32621790/101538341-b8da3180-397b-11eb-984c-09093cc9c823.jpeg)

![WhatsApp Image 2020-12-08 at 17 29 34](https://user-images.githubusercontent.com/32621790/101538366-c0013f80-397b-11eb-826e-3db5ea2bef71.jpeg)

@openarun 
@anantamishra

**Comment by openarun** [comment]
I am closing this bug as I believe the latest release of UbuntuDDE has this issue fixed. If you find this bug in the latest releases, please feel free to re-open and mention your UbuntuDDE Remix version.
