### ISSUE TITLE
Ubuntu-DDE 20.10 with error in _usr_bin_deepin-terminal.1000.crash

### ISSUE THREAD

**Issue by serial02** [UbuntuDDE/bugs#71]
Hello Ubuntu-DDE Team 20.10

After restarting the message to send the report appeared, but as we know that the sending is not carried out, I am attaching image and report here.

[_usr_bin_deepin-terminal.1000.crash.zip](https://github.com/UbuntuDDE/bugs/files/5665764/_usr_bin_deepin-terminal.1000.crash.zip)

[_usr_bin_stacer.1000.crash.zip](https://github.com/UbuntuDDE/bugs/files/5665774/_usr_bin_stacer.1000.crash.zip)

![Screen Capture_apport-gtk_20201208232721](https://user-images.githubusercontent.com/32621790/101627888-c9cb8700-39fd-11eb-8d5a-f52249e63654.png)

![Screen Capture_stacer_20201209090701](https://user-images.githubusercontent.com/32621790/101628009-f384ae00-39fd-11eb-9b72-3481c6a907b8.png)

@openarun 
@anantamishra

**Comment by openarun** [comment]
I am closing this bug because groovy is EOL and I believe the latest release of UbuntuDDE has this issue fixed. If you find this bug in the latest releases, please feel free to re-open and mention your UbuntuDDE Remix version.
