### ISSUE TITLE
Smart Hide leaves a shadow task bar

### ISSUE THREAD

**Issue by davethecanuck** [UbuntuDDE/bugs#72]
**Describe the bug**
I have my taskbar in "fashion mode" at the bottom with "smart hide". There is an odd quirk where it hides when an application is full screen but leaves a "shadow" of the taskbar behind. If I give the taskbar focus, and then quickly take away focus again the "shadow" hides. If I'm not quick enough, the shadow remains. Note that this "shadow"  is really a fully functional taskbar, not just an artifact.

**To Reproduce**
1. Put taskbar in fashion mode on the bottom of the screen
2. Put taskbar in smart-hide mode
3. Open an application in full screen mode -> taskbar properly hides
4. Move mouse cursor to bottom of screen -> taskbar properly reappears
5. Move mouse to middle of screen -> taskbar hides, but leaves a functional shadow copy of itself behind
6. Move mouse to bottom of screen, leave for 1 second, and move mouse back up -> shadow taskbar remains
7. Move mouse to bottom of screen and immediately back up to middle of screen -> shadow taskbar disappears

**Expected behavior**
For #5 and #6, I'd expect the taskbar to disappear and no shadow taskbar to be left behind.

**Screenshots**

**Desktop (please complete the following information):**
 - Version 20.10

**Additional context**
This was not happening with the original 20.10 install, but appears to have started with a recent update.

**Comment by anantamishra** [comment]
Hi there,
This issue was already fixed and the patch was sent via updates. And can't reproduce it anymore.
Feel free to reopen if it's an issue again with appropriate steps to reproduce.
Thanks!
