### ISSUE TITLE
I am unable to update UbuntuDDE 

### ISSUE THREAD

**Issue by Asriel115** [UbuntuDDE/bugs#73]
I have no clue why it won't update, I am still a noob to Linux but this is just not good at all. 
![Screen_Capture_20201215022730](https://user-images.githubusercontent.com/63687010/102245558-b459cf80-3ecb-11eb-9d1a-f35fba7f77f8.png)
I tried everything I knew from installing the updates manually through the terminal, nothing on Google could help with this issue either so I'm left to bringing it up here. Now I am probably personally going to just switch to Deepin after this but I wanted to bring up this issue beforehand.

**Comment by anantamishra** [comment]
Hello @Asriel115 , You can simply update your system via the command given below:
``` 
sudo apt update && sudo apt upgrade
```
or you can use the **Software Updater** to update your system.
