### ISSUE TITLE
Application Request: Deepin Image Viewer

### ISSUE THREAD

**Issue by ghost** [UbuntuDDE/bugs#74]
The current version of Deepin Image Viewer is just from the official Ubuntu repo - 5.0.0, which is pretty old and doesn't fit with DDE 20's design.
![Screen Capture_deepin-image-viewer_20201222190951](https://user-images.githubusercontent.com/56656996/102954851-5740b980-4489-11eb-8447-47561ad891fb.png)
https://github.com/linuxdeepin/deepin-image-viewer/

**Comment by anantamishra** [comment]
The latest release of the Package Deepin Image Viewer is released . You can try it by updating your system.

**Comment by anantamishra** [comment]
#closed

**Comment by ghost** [comment]
> The latest release of the Package Deepin Image Viewer is released . You can try it by updating your system.

Awesome, thanks!
