### ISSUE TITLE
Filesystem check cannot be interrupted when booting the live system

### ISSUE THREAD

**Issue by scroom** [UbuntuDDE/bugs#75]
**Describe the bug**
I started the live system from a USB stick. File systems were checked during the boot. CTRL+C could not stop this.

**To Reproduce**
1. Start the Live System
2. If the filesystem-check starts press CTRL+C

**Expected behavior**
The filesystem-check should be stopped if I want so.

**Desktop (please complete the following information):**
 - Version 20.10

**Comment by openarun** [comment]
I am closing this bug as I believe the latest release of UbuntuDDE has this issue fixed. If you find this bug in the latest releases, please feel free to re-open and mention your UbuntuDDE Remix version.
