### ISSUE TITLE
Window buttons are very different in size

### ISSUE THREAD

**Issue by scroom** [UbuntuDDE/bugs#76]
**Describe the bug**
As described above, the Windows buttons (min, max, close) are very different in size. Attached is a screenshot of Firefox (small) and the settings (large). Does not match the otherwise very nice look. Scaling is set to 1,5.

**Expected behavior**
Window buttons have the same size.

**Screenshots**
![Screen Capture_select-area_20210104015520](https://user-images.githubusercontent.com/5347731/103493266-8adbf600-4e30-11eb-9253-c1735a39a253.png)

**Desktop (please complete the following information):**
 - Version 20.10

**Comment by scroom** [comment]
Another screenshot:
Firefox (smallest size), Signal-Desktop (medium) and Settings (large):
![Screen Capture_select-area_20210104020256](https://user-images.githubusercontent.com/5347731/103493360-19507780-4e31-11eb-8d9f-7ccce429736b.png)

As can be seen, not only the size is very different, but also the color of the window frames and the curvature of the window.

**Comment by justforlxz** [comment]
We need to provide gtk with the same window theme, which takes some time, and the old gtk theme can no longer be applied to the current dtk design. :)

**Comment by openarun** [comment]
I am closing this bug as I believe the latest release of UbuntuDDE has this issue fixed. If you find this bug in the latest releases, please feel free to re-open and mention your UbuntuDDE Remix version.
