### ISSUE TITLE
German term for standby does not fit in the power off menu and is truncated

### ISSUE THREAD

**Issue by scroom** [UbuntuDDE/bugs#78]
**Describe the bug**
As described above. The term is "Bereitschaftszustand". The B and the d are cut off.

**Expected behavior**
Term should be completely readable.

**Screenshots**
![Bildschirmfoto vom 2021-01-08 01-54-47](https://user-images.githubusercontent.com/5347731/103961430-c2aaac80-5154-11eb-89b8-aaccf87db5ce.png)

**Desktop (please complete the following information):**
 - Version 20.10

**Comment by openarun** [comment]
I am closing this bug as I believe the latest release of UbuntuDDE has this issue fixed. If you find this bug in the latest releases, please feel free to re-open and mention your UbuntuDDE Remix version.
