### ISSUE TITLE
Filemanager crashes when changing the order of bookmarks

### ISSUE THREAD

**Issue by scroom** [UbuntuDDE/bugs#79]
**Describe the bug**
When trying to change the order of the bookmarks in the file manager by drag and drop, the file manager crashes

**To Reproduce**
1. Open the filemanager
2. try to move one of your bookmarks to another place
3. filemanager crashes

**Expected behavior**
It should be possible to change the order of bookmarks

**Desktop (please complete the following information):**
 - Version 20.10

**Comment by openarun** [comment]
With the latest update, the file-manager doesn't crash when changing the order of bookmark. :) So, I am closing this bug, if it persists or if you have any additional query, please feel free to re-open.
Thanks!

**Comment by scroom** [comment]
@openarun It is still crashing on both systems I've installed UbuntuDDE on. Sadly I can't reopen the bug. Can you reopen it, please?

**Comment by openarun** [comment]
I am unable to reproduce it, please update the issue with the proper reproducible steps.
Thanks!

**Comment by scroom** [comment]
On both of my systems these are the steps to reproduce the problem:

1. Open the filemanager
2. try to move one of your bookmarks to another place
3. filemanager crashes

**Comment by anantamishra** [comment]
> On both of my systems these are the steps to reproduce the problem:
> 
>     1. Open the filemanager
> 
>     2. try to move one of your bookmarks to another place
> 
>     3. filemanager crashes

Please let us know the version of dde-file-manager you are using on your system

**Comment by scroom** [comment]
@anantamishra It is 5.2.0.85

![Bildschirmfoto vom 2021-01-22 01-16-19](https://user-images.githubusercontent.com/5347731/105428342-8183c380-5c4f-11eb-8c63-843173b5bc33.png)

**Comment by openarun** [comment]
I am closing this bug because groovy is EOL. If you find this bug in the latest releases, please feel free to re-open and mention your UbuntuDDE Remix version.
