### ISSUE TITLE
Freeze When Shutdown

### ISSUE THREAD

**Issue by chimemoo** [UbuntuDDE/bugs#8]
**Describe the bug**
when i shutdown my laptop, the laptop can't turn off only shows a dark screen. It same if i shutdown from my terminal command.

**To Reproduce**
1. Go to Power
2. Click on Shutdown

**Expected behavior**
The laptop should be shutdown

**Desktop :**
 - Ubuntu DDE 20.04 Remix Edition
- Type 64 Bit 
- Processor Intel(R) Core (TM) i5-4210M
- CPU @ 2.60 GHz x 4
- Memory 7.47 GB

**Comment by anantamishra** [comment]
Please look that the issue is solved or not in the latest point release of UbuntuDDE  20.04 i.e. 20.04.1 and reply the conclusion here.
try upgrading the release with the following command:
```
sudo apt-get update && sudo apt-get upgrade
```
