### ISSUE TITLE
Dock becomes transparent, not blurred anymore

### ISSUE THREAD

**Issue by dylanmartinezs** [UbuntuDDE/bugs#80]
**Describe the bug**
The dock suddently looses its blur and becomes fully transparent

**To Reproduce**
Not quite sure, but it appears after being hid by a fullscreen window in smart hide, and reappearing (not always).

**Expected behavior**
Dock should always blur what's behind it

**Screenshots**
![Screen Capture_dde-desktop_20210113001005](https://user-images.githubusercontent.com/25688218/104385746-15f57400-5534-11eb-82c5-7878885c5e42.png)

**Desktop (please complete the following information):**
 - Version 20.10 latest as of 13/01/2021

**Additional context**
I think I've seen this in Deepin a couple of months ago

**Comment by rindia** [comment]
@openarun @anantamishra 
i am also facing same issues after getting thee latest update

**Comment by openarun** [comment]
Did you try installing/changing to an appropriate graphics driver?

**Comment by openarun** [comment]
I am closing this bug because groovy is EOL. If you find this bug in the latest releases, please feel free to re-open and mention your UbuntuDDE Remix version.
