### ISSUE TITLE
Filemanager: no more connections via sftp possible

### ISSUE THREAD

**Issue by scroom** [UbuntuDDE/bugs#82]
**Describe the bug**
Since the last update I can no longer connect via sftp with the filemanager.

**To Reproduce**
1. Try to "connect to server" in the filemanager
2. Error message appears. Files and Folders are loaded but you cannot access it.

**Expected behavior**
As before the updates. Allow connections via sftp

**Screenshots**
![Bildschirmfoto vom 2021-01-14 01-22-58](https://user-images.githubusercontent.com/5347731/104528526-d5ffc100-5607-11eb-81ea-46536f7971f8.png)

**Desktop (please complete the following information):**
 - Version 20.10

**Comment by openarun** [comment]
I am closing this bug as I believe the latest release of UbuntuDDE has this issue fixed. If you find this bug in the latest releases, please feel free to re-open and mention your UbuntuDDE Remix version.
