### ISSUE TITLE
Dock changes the location randomly 

### ISSUE THREAD

**Issue by rindia** [UbuntuDDE/bugs#84]
**Describe the bug**
Dock location is changing randomly  

Steps - 
1. set main screen as default 
2. extended monitor - open any application  and move to extended screen.
3. dock location moving from main screen to extended monitor and vice versa randomly 

@openarun @anantamishra

**Comment by rindia** [comment]
@openarun @anantamishra

**Comment by samratsuzil** [comment]
I have explained this on https://github.com/UbuntuDDE/bugs/issues/81 . Please have a look at this if this might be helpful.

**Comment by anantamishra** [comment]
Duplicate of #81

**Comment by openarun** [comment]
The setting to set/unset the dock to the primary monitor is missing in the control center for now.

But as a workaround, you can execute the following command to set the dock fixed to the primary monitor.

`$ gsettings set com.deepin.dde.dock.mainwindow only-show-primary true`

Hope that helps you. If this solves for you, feel free to close the issue :)

**Comment by rindia** [comment]
@openarun  Thank you so much for this, highly appreciated 
@anantamishra
