### ISSUE TITLE
Icon of DDE apps in the upper left corner are pixelated

### ISSUE THREAD

**Issue by scroom** [UbuntuDDE/bugs#85]
**Describe the bug**
As decribed above. Resolution is 2560*1440, scaling is set to 1,25.
I'm using UbuntuDDE 20.10.
Here comes a screenshot:
![Bildschirmfoto vom 2021-01-22 01-15-04](https://user-images.githubusercontent.com/5347731/105429213-3a96cd80-5c51-11eb-9247-bb37bc1b85e0.png)
Maybe it is the same problem I've had in the DDE-Store?: https://github.com/dekzi/dde-store/issues/15

**Comment by openarun** [comment]
I am closing this bug because groovy is EOL and I believe the latest release of UbuntuDDE has this issue fixed. If you find this bug in the latest releases, please feel free to re-open and mention your UbuntuDDE Remix version.
