### ISSUE TITLE
Single Notifications cannot be disabled in Control Center -> Notifications

### ISSUE THREAD

**Issue by mrsleepi** [UbuntuDDE/bugs#88]
**Describe the bug**
App Notifications can't be disabled in the control center -> Notification. No matter if you set to "Do not disturb", deactivate any of the single options (Play a sound, Show in Notification Center) or deactivate it completely, it does not have any effect for the application you made the changes for.

**Expected behavior**
Notifications should be disabled when "Do Not Disturbed" is enabled, same with deactivating any single notification option for a specific application.

**Screenshots**
![ubuntudde_notification](https://user-images.githubusercontent.com/77987326/105747468-b9815400-5f38-11eb-8620-783cbd9f3a6b.png)

**Desktop (please complete the following information):**
 - Version 20.1

**Additional context**
Tried the original Deepin Linux OS 20.1 as well where it shows the same behaviour

**Comment by openarun** [comment]
I am closing this bug as I believe the latest release of UbuntuDDE has this issue fixed. If you find this bug in the latest releases, please feel free to re-open and mention your UbuntuDDE Remix version.
