### ISSUE TITLE
Wifi password not saved

### ISSUE THREAD

**Issue by zaivala** [UbuntuDDE/bugs#89]
**Describe the bug**
I have UbuntuDDE Remix installed on a Dell Inspiron 7353 laptop and a System76 Kudu 3. On both machines, it does not save the wifi password, and I have to enter it every time I boot up, log in, or wake up my screen. Every time. Both machines use common Intel wifi adapters.  Inspiron has Intel 3165, Kudu has Intel 8260.

**To Reproduce**
1. Boot up to Ubuntu DDE
or 
1. Log in to Ubuntu DDE
or 
1. Wake up Ubuntu DDE (open screen lid)

**Expected behavior**
The wifi should automatically reconnect.

**Desktop (please complete the following information):**
 - UbuntuDDE Remix 20.10

**Additional context**
I talked with Arun about this extensively, and he suggested I file the bug.

**Comment by openarun** [comment]
With the current updates, it should be resolved. Please let me know about this.

**Comment by Rancesk** [comment]
> With the current updates, it should be resolved. Please let me know about this.

Sorry, the problem persist after all update.

**Comment by zaivala** [comment]
The problem no longer persists on my various machines. Thank you for remedying it.

**Comment by Rinzler-op** [comment]
Hey, i'm having the same problem but on UbuntuDDE Remix 21.04. 
I think the UbuntuDDE team is onto something very special with this distro and id like to help as much as i can!

**Comment by openarun** [comment]
I am closing this bug as I believe the latest release of UbuntuDDE has this issue fixed. If you find this bug in the latest releases, please feel free to re-open and mention your UbuntuDDE Remix version.
