### ISSUE TITLE
Monitor brightness drops after unlocking screen on dual monitor setup

### ISSUE THREAD

**Issue by GrimReaper420** [UbuntuDDE/bugs#9]
When I lock the screen (with win+L) the system works fine. However, after I enter my password and unlock the system one of the monitors (the primary monitor, I have 2 connected) goes dark, it's still on but the brightness is extremely low. I have an almost fresh install with only Google Chrome, Pycharm, and python 3  installed. This has happened every time the screen is locked but the brightness is fixed after a reboot.

I have AMD integrated graphics and I have an extra Nvidia graphics card with the open-source drivers installed:

$ lspci | grep VGA
01:00.0 VGA compatible controller: NVIDIA Corporation GK208B [GeForce GT 710] (rev a1)
07:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Raven Ridge [Radeon Vega Series / Radeon Vega Mobile Series] (rev c6)

**Comment by anantamishra** [comment]
Can you please mention your Laptop Model too

**Comment by GrimReaper420** [comment]
I'm using a PC.

CPU: AMD Ryzen 5 3400g with Radeon Vega Graphics
Motherboard:
- Manufacturer: Gigabyte Technology Co., Ltd.
- Product Name: B450M DS3H-CF
GPU: GeForce GT 710

Default GPU: Radeon Vega Graphics
Nvidia GPU Driver: Ver 440 (proprietary)

**Comment by openarun** [comment]
I am closing this bug as I believe the latest release of UbuntuDDE has this issue fixed. If you find this bug in the latest releases, please feel free to re-open and mention your UbuntuDDE Remix version.
