### ISSUE TITLE
Terminal not maximize in extended monitor - not fit in monitor size

### ISSUE THREAD

**Issue by rindia** [UbuntuDDE/bugs#90]
Terminal not maximize in extended monitor 

![Screen Capture_select-area_20210426093211](https://user-images.githubusercontent.com/22998037/116027405-6f605980-a672-11eb-931e-2e900633f8df.jpg)

@openarun @anantamishra

**Comment by openarun** [comment]
What is your deepin-terminal version and UbuntuDDE Remix version?

**Comment by rindia** [comment]
@openarun 

![Screen Capture_select-area_20210503193903](https://user-images.githubusercontent.com/22998037/116886968-5b56c200-ac47-11eb-8cb2-af8b92973516.jpg)

**Comment by openarun** [comment]
ok, what is your deepin-terminal package version?
You can check by running the following command in terminal:
$ dpkg -l deepin-terminal
Thanks!

**Comment by rindia** [comment]
![Screen Capture_deepin-terminal_20210503194249](https://user-images.githubusercontent.com/22998037/116887280-c3a5a380-ac47-11eb-86a7-e2ae2274eddb.jpg)


@openarun

**Comment by openarun** [comment]
I am closing this bug as I believe the latest release of UbuntuDDE has this issue fixed. If you find this bug in the latest releases, please feel free to re-open and mention your UbuntuDDE Remix version.
