### ISSUE TITLE
Black screen comes after booting - serious issue

### ISSUE THREAD

**Issue by rindia** [UbuntuDDE/bugs#91]
Hi,

When i try to boot the system, after few second screen goes to completely  blank and not able to enter my login password.

every time i need to restart system until it fix.

it is a big pain area for me.

I am using latest OS with fresh installation.

@openarun @anantamishra

**Comment by DariusIurca** [comment]
There is a workaround for this problem. Press ESC when the login screen flashes and then update everything.

**Comment by DariusIurca** [comment]
#11

**Comment by rindia** [comment]
working now as expected after getting OAT update
