### ISSUE TITLE
UbuntuDDE 21.04: Unable to install Deepin-Music

### ISSUE THREAD

**Issue by Rancesk** [UbuntuDDE/bugs#92]
UbuntuDDE 21.04 doesn't install "Deepin-Music" because require "gvfs-bin".

--- VIA TERMINAL ---
sudo apt install deepin-music
[sudo] password for user: 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 deepin-music : Depends: gvfs-bin but it is not installable
E: Unable to correct problems, you have held broken packages.
---

![Screen Capture_synaptic_20210503145648](https://user-images.githubusercontent.com/47328128/116878632-ecb23e00-ac1f-11eb-899a-4f2e0ab2464c.png)

**Comment by anantamishra** [comment]
Hi there,
The patch for the above-mentioned issue has been sent via an update, please try installing deepin-music and let us know if any issue comes in.
Thanks!
