### ISSUE TITLE
UbuntuDDE 21.04: Unable to install "Deepin-Draw"

### ISSUE THREAD

**Issue by Rancesk** [UbuntuDDE/bugs#93]
**Describe the bug**
UbuntuDDE 21.04 report an error when try to install deepin-draw.

**To Reproduce**
From terminal digit:
sudo apt install deepin-draw

Reply from terminal:
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:
The following packages have unmet dependencies:
deepin-draw : Depends: deepin-picker-cli but it is not installable
E: Unable to correct problems, you have held broken packages.

**Expected behavior**
Deepin-draw package installed.

**Screenshots**
![Screen Capture_deepin-terminal_20210503153302](https://user-images.githubusercontent.com/47328128/116882651-fab68d80-ac24-11eb-9840-ca1bd9d1d76b.png)

**Desktop
 - Version 21.04

**Additional context**
Deepin-draw require "deepin-picker-cli" but it is not installable.

**Comment by anantamishra** [comment]
Hi there,
The patch regarding this issue has been sent via updates. You can try installing deepin-draw now.
Thanks!

**Comment by anantamishra** [comment]
Hi there,
The patch regarding this issue has been sent via updates. You can try installing deepin-draw.
Thanks!
