### ISSUE TITLE
UbuntuDDE 21.04: Deepin-Reader doesn't start

### ISSUE THREAD

**Issue by Rancesk** [UbuntuDDE/bugs#94]
**Describe the bug**
Deepin-Reader doesn't start.

**To Reproduce**
1. Open Terminal
2. Digit "deepin-reader" and press enter
3. See error:
deepin-reader: error while loading shared libraries: libdeepin-poppler.so.100: cannot open shared object file: No such file or directory

**Expected behavior**
Start Deepin-Reader

**Desktop**
 - Version 21.04

**Additional context**
Deepin-reader require libdeepin-poppler.so.100 but there isn't in the repository.

** Thanks in advance **

**Comment by openarun** [comment]
I am closing this bug as I believe the latest release of UbuntuDDE has this issue fixed. If you find this bug in the latest releases, please feel free to re-open and mention your UbuntuDDE Remix version.
