### ISSUE TITLE
DeepinDDE 21.04: Package Installer doesn't work

### ISSUE THREAD

**Issue by Rancesk** [UbuntuDDE/bugs#95]
**Describe the bug**
When I try to install an application via Package Installer GUI, I receive an error: "Damaged dependencies: libgcc-s1".
If I try to install the same application via Terminal it work fine.

**To Reproduce**
Double click on a .deb file or drag and drop it on Package Installer GUI.

**Expected behavior**
.deb package installed

**Desktop**
 - Version 21.04

**Comment by openarun** [comment]
I am closing this bug because hirsute is EOL and I believe the latest release of UbuntuDDE has this issue fixed. If you find this bug in the latest releases, please feel free to re-open and mention your UbuntuDDE Remix version.
