### ISSUE TITLE
Deepin 21.04: Deepin File Manager doesn't accept square bracket into file name

### ISSUE THREAD

**Issue by Rancesk** [UbuntuDDE/bugs#96]
**Describe the bug**
Unable to name or rename a file inside Deepin File Manager with square bracket.

**To Reproduce**
1. Open 'Deepin File Manager'
2. Click on a file and press F2 to rename it
3. Insert a square bracket into the name
4. Deepin File Manager remove it

**Expected behavior**
A file with a square bracket [] into the name; example: "Music Name [Author].mp3"

**Desktop**
 - Version 21

**Comment by openarun** [comment]
The file manager does prompt a warning that square brackets are not accepted in the file manager.
