### ISSUE TITLE
Clock hands in settings are not displayed correctly

### ISSUE THREAD

**Issue by radoslew** [UbuntuDDE/bugs#97]
**Describe the bug**
Clock hands in settings are not displayed correctly.

**To Reproduce**
Go to 'Settings' and check clock options.

**Expected behavior**
It should look just like in previous version - normal long clock hands with animation.

**Screenshots**

![](https://cdn.discordapp.com/attachments/762005981533569054/851253283203973120/up.PNG)

**Desktop (please complete the following information):**
 - Version 21.04 (the latest one at the moment)

**Additional context**
None

**Comment by openarun** [comment]
I am closing this bug as I believe the latest release of UbuntuDDE has this issue fixed. If you find this bug in the latest releases, please feel free to re-open and mention your UbuntuDDE Remix version.
