### ISSUE TITLE
Is it possible to make IBus app look more coherent?

### ISSUE THREAD

**Issue by radoslew** [UbuntuDDE/bugs#98]
**Describe the bug**
Is it possible to make IBus app look more coherent? It looks bad and doesn't seem to be working very well too. Some changes or maybe even different app? Can I change it myself?

**To Reproduce**
Just take a look at it. You can also try to mess around "inside" this app.

**Expected behavior**
I want it to be clear looking and coherent. It also should be easy to use - just like the rest of deepin settings.

**Screenshots**

![](https://cdn.discordapp.com/attachments/762005981533569054/851253899146559498/up2.PNG)

**Desktop (please complete the following information):**
 - Version 21.04
 
**Additional context**
None

**Comment by openarun** [comment]
I am closing this bug as I believe the latest release of UbuntuDDE has this issue fixed. If you find this bug in the latest releases, please feel free to re-open and mention your UbuntuDDE Remix version.
