### ISSUE TITLE
UbuntuDDE Remix 21.04 freezing

### ISSUE THREAD

**Issue by Rinzler-op** [UbuntuDDE/bugs#99]
**Describe the bug**

**To Reproduce**
1. i Go to 'control center'
2. into the wifi settings of my network and turn on auto connect.
3. Scroll down to 'try and type password and save settings'
4. See error the control center freezes 

**Expected behavior**
The system basically keeps freezing and i don't know why because i am already using efficient mode on a rysen 5, 16gb ram and a 500gb ssd.    

 
**Screenshots**

**Desktop (please complete the following information):**
 - Version [UbuntuDDE Remix 21.04]

**Additional context**
Add any other context about the problem here;
This also happens with the wallpaper, when i right click to change it there's no response. and when i do finally change it (if it responds) then go to display settings and after i change display settings, it goes back to default wallpaper.

**Comment by openarun** [comment]
I am closing this bug because hirsute is EOL and I believe the latest release of UbuntuDDE has this issue fixed. If you find this bug in the latest releases, please feel free to re-open and mention your UbuntuDDE Remix version.
